const supported=['en','pt','es','de'];
let saved;try{saved=localStorage.getItem('ze-language')}catch{}
let lang=supported.includes(saved)?saved:(navigator.languages||[navigator.language]).map(x=>x.toLowerCase().split('-')[0]).find(x=>supported.includes(x))||'en';
const page=document.body.dataset.page;
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const t=content[lang];if(typeof homeCopy!=='undefined')t.nav=homeCopy[lang].nav;document.documentElement.lang={en:'en',pt:'pt-BR',es:'es-419',de:'de'}[lang];document.title=`Zonneveld Engineering — ${page!=='home'?(page==='loadout'?'Load Out '+document.body.dataset.loadout:page==='cadeler'?'Cadeler':page==='vessel'?'WIND ORCA':'Hornsea 3'):t.tag}`;
const home=page!=='home'?'/':'#home';
const nav=page!=='home'?`${page==='loadout'?'<a href="/19/19/19/">← Hornsea 3</a>':page==='manufactura'?'<a href="/manufactura/">Manufactura</a>':''}<a href="${home}">${t.home}</a>`:t.nav.map((s,i)=>`<a href="#${['expertise','about','contact'][i]}">${s}</a>`).join('');
const header=`<a class="skip" href="#main">${t.skip}</a><header><div class="wrap nav"><a class="brand" href="${home}" aria-label="Zonneveld Engineering"><span class="mark" aria-hidden="true"><img src="/zonneveld.png" alt=""></span><span class="brand-text">Zonneveld Engineering</span></a><div class="nav-tools"><nav aria-label="${t.home}">${nav}</nav><select class="language" aria-label="${t.language}">${[['en','English'],['pt','Português'],['es','Español'],['de','Deutsch']].map(([k,v])=>`<option value="${k}" ${k===lang?'selected':''}>${v}</option>`).join('')}</select></div></div></header>`;
const art=`<div class="art" aria-hidden="true"><svg viewBox="0 0 480 440" fill="none" xmlns="http://www.w3.org/2000/svg"><g stroke="#777" stroke-width=".7"><path d="M0 110H480M0 220H480M0 330H480M120 0V440M240 0V440M360 0V440M0 0L480 440M0 440L480 0"/><circle cx="240" cy="220" r="175"/><circle cx="240" cy="220" r="142"/><circle cx="240" cy="220" r="109"/><circle cx="240" cy="220" r="76"/></g><circle cx="240" cy="220" r="175" stroke="#ffc000" stroke-width="2" stroke-dasharray="275 1100" transform="rotate(-90 240 220)"/><circle cx="240" cy="220" r="7" fill="#ffc000"/><path d="M240 220L415 220" stroke="#ffc000" stroke-width="1.5"/></svg><div class="art-label"><span>${t.art}</span><span>Z / E</span></div></div>`;
const homepage=page==='home'?homeView(lang,t):'';
const videoPage=page==='home'?'':page==='manufactura'?manufacturaView(lang,t):archiveView(page,lang,t);
document.body.innerHTML=header+(page!=='home'?videoPage:homepage)+`<footer><div class="wrap footer-inner"><span class="footer-name">Zonneveld Engineering</span><small>© 2026 Daniel Zonneveld</small><a href="${home}">${page!=='home'?'← '+t.home:t.top+' ↑'}</a></div></footer>`;
if(page==='manufactura'){document.title=manufacturaCurrent().title==='Zonneveld Manufactura'?'Zonneveld Manufactura':manufTitle(document.body.dataset.path,lang)+' — Zonneveld Manufactura';setupManufactura();}
document.querySelector('.language').addEventListener('change',e=>{lang=e.target.value;try{localStorage.setItem('ze-language',lang)}catch{}render();document.querySelector('.language').focus()});}
render();
