const archiveCopy={
 en:{vessels:'Vessels',projects:'Projects',operations:'Operations',view:'View videos',records:'video records',source:"Personal recordings shared selectively for private, non-commercial use, primarily for documentation and reference. Please do not redistribute or share on social media without prior authorization from those involved."},
 pt:{vessels:'Embarcações',projects:'Projetos',operations:'Operações',view:'Ver vídeos',records:'registros em vídeo',source:"Registros pessoais compartilhados de forma seletiva para uso privado e não comercial, principalmente para documentação e referência. Não redistribuir nem compartilhar em redes sociais sem a devida autorização dos envolvidos."},
 es:{vessels:'Embarcaciones',projects:'Proyectos',operations:'Operaciones',view:'Ver videos',records:'registros en video',source:"Grabaciones personales compartidas de forma selectiva para uso privado y no comercial, principalmente como registro y referencia. No redistribuir ni compartir en redes sociales sin la debida autorización de las personas involucradas."},
 de:{vessels:'Schiffe',projects:'Projekte',operations:'Einsätze',view:'Videos ansehen',records:'Videoaufzeichnungen',source:"Persönliche Aufnahmen, die gezielt zur privaten, nicht kommerziellen Nutzung geteilt werden, vor allem zur Dokumentation und als Referenz. Bitte nicht ohne vorherige Zustimmung der Beteiligten weitergeben oder in sozialen Medien teilen."}
};
function dateText(iso,language){const locale={en:'en-GB',pt:'pt-BR',es:'es-419',de:'de-DE'}[language];const parts=new Intl.DateTimeFormat(locale,{day:'2-digit',month:'long',year:'numeric',timeZone:'UTC'}).formatToParts(new Date(iso+'T12:00:00Z'));return ['day','month','year'].map(k=>parts.find(p=>p.type===k).value).join('.');}
function dateRange(v,l){return dateText(v.startDate,l)+(v.endDate!==v.startDate?' – '+dateText(v.endDate,l):'');}
function hoursText(v,l,t){return v.executionHours==null?t.unset:new Intl.NumberFormat({en:'en-GB',pt:'pt-BR',es:'es-ES',de:'de-DE'}[l],{minimumFractionDigits:2,maximumFractionDigits:2}).format(v.executionHours)+' h';}
function archiveView(page,l,t){const a=archiveCopy[l];const lo=Number(document.body.dataset.loadout);const list=videos.filter(v=>v.loadout===lo).sort((a,b)=>a.startDate.localeCompare(b.startDate)||a.endDate.localeCompare(b.endDate));let title,overline,children=[];
 if(page==='cadeler'){title='Cadeler';overline=a.vessels;children=[['WIND ORCA','/19/19/',a.projects]];}
 else if(page==='vessel'){title='WIND ORCA';overline='Cadeler';children=[['Hornsea 3','/19/19/19/','Load Out 5 · Load Out 6']];}
 else if(page==='project'||page==='videos'){title='Hornsea 3';overline='WIND ORCA';children=[5,6].map(n=>['Load Out '+n,'/19/19/19/'+((n-4)*19)+'/','']);}
 else {title='Load Out '+lo;overline='WIND ORCA · Hornsea 3';}
 const tiles=children.map(([name,url,detail])=>`<a class="archive-card" href="${url}"><span><h2>${name}</h2>${detail?`<p>${detail}</p>`:''}</span><span aria-hidden="true">↗</span></a>`).join('');
 const rows=list.map((v,i)=>`<article class="video-row ${v.orientation==='portrait'?'vertical':''}" id="video-${v.id}"><div class="player" style="--video-ratio:${v.aspectRatio||'16/9'}"><iframe loading="${i<2?'eager':'lazy'}" src="https://www.youtube-nocookie.com/embed/${v.id}" title="${esc(v.title[l])}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><div class="video-copy"><h2>${esc(v.title[l])}</h2><div class="video-meta"><p>${dateRange(v,l)}</p>${v.executionHours==null?'':`<p>${hoursText(v,l,t)}</p>`}</div><p>${esc(v.description[l])}</p><a class="video-source" href="https://www.youtube.com/watch?v=${v.id}" target="_blank" rel="noopener noreferrer">${t.watch} ↗</a></div></article>`).join('');
 return `<main id="main" class="wrap archive"><div class="videos-intro"><p class="eyebrow">${overline}</p><h1>${title}</h1></div>${children.length?`<div class="archive-cards">${tiles}</div>`:`<section class="video-list">${rows}</section>`}<p class="source-note">${a.source}</p></main>`;
}
