/* Impressum e Datenschutzerklärung — RASCUNHO 02/10/2026.
   A versão alemã é a juridicamente vinculante; as demais são traduções de cortesia.
   Campos marcados com legalTodo() precisam ser preenchidos/confirmados por Daniel antes de publicar. */
const legalTodo=s=>`<mark class="legal-todo">${s}</mark>`;
const legalMail='<a href="mailto:info@zonneveldengineering.com">info@zonneveldengineering.com</a>';
const legalAddress='Zonneveld Engineering UG (haftungsbeschränkt)<br>Am Hohenberg 13<br>27711 Osterholz-Scharmbeck';
const legalMD='Daniel Zonneveld Coltro';
const legalAuthority='Die Landesbeauftragte für den Datenschutz Niedersachsen<br>Prinzenstraße 5<br>30159 Hannover';
const legalGoogle='Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland';
const legalAdobe='Adobe Systems Software Ireland Limited, 4–6 Riverwalk, Citywest Business Campus, Dublin 24, Irland';
const legalGitHub='GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, USA';

const legalCopy={
impressum:{
de:{title:'Impressum',sections:[
['Angaben gemäß § 5 DDG',`<p>${legalAddress}<br>Deutschland</p>`],
['Vertreten durch',`<p>${legalMD}, Geschäftsführer</p>`],
['Kontakt',`<p>E-Mail: ${legalMail}</p>`],
['Registereintrag',`<p>Eintragung im Handelsregister<br>Registergericht: Amtsgericht Walsrode<br>Registernummer: HRB 213510</p>`],
['Umsatzsteuer-ID',`<p>Umsatzsteuer-Identifikationsnummer gemäß § 27a Umsatzsteuergesetz: DE461455043</p>`],
['Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV',`<p>${legalMD}, Anschrift wie oben</p>`]]},
en:{title:'Impressum',note:'Legal notice required under German law. This is a courtesy translation; the German version is legally binding.',sections:[
['Information pursuant to § 5 DDG (German Digital Services Act)',`<p>${legalAddress}<br>Germany</p>`],
['Represented by',`<p>${legalMD}, Managing Director (Geschäftsführer)</p>`],
['Contact',`<p>Email: ${legalMail}</p>`],
['Register entry',`<p>Entered in the German commercial register (Handelsregister)<br>Register court: Amtsgericht Walsrode<br>Registration number: HRB 213510</p>`],
['VAT ID',`<p>VAT identification number pursuant to § 27a of the German VAT Act (UStG): DE461455043</p>`],
['Responsible for content pursuant to § 18(2) MStV',`<p>${legalMD}, address as above</p>`]]},
pt:{title:'Impressum',note:'Identificação legal exigida pela legislação alemã. Esta é uma tradução de cortesia; a versão em alemão é a juridicamente válida.',sections:[
['Informações conforme o § 5 DDG (Lei alemã de Serviços Digitais)',`<p>${legalAddress}<br>Alemanha</p>`],
['Representada por',`<p>${legalMD}, diretor-geral (Geschäftsführer)</p>`],
['Contato',`<p>E-mail: ${legalMail}</p>`],
['Registro comercial',`<p>Inscrita no registro comercial alemão (Handelsregister)<br>Tribunal de registro: Amtsgericht Walsrode<br>Número de registro: HRB 213510</p>`],
['Identificação fiscal (USt-IdNr.)',`<p>Número de identificação para fins de IVA conforme o § 27a da Lei alemã do IVA (UStG): DE461455043</p>`],
['Responsável pelo conteúdo conforme o § 18, parágrafo 2, MStV',`<p>${legalMD}, endereço indicado acima</p>`]]},
es:{title:'Impressum',note:'Aviso legal exigido por la legislación alemana. Esta es una traducción de cortesía; la versión en alemán es la jurídicamente vinculante.',sections:[
['Información según el § 5 DDG (Ley alemana de Servicios Digitales)',`<p>${legalAddress}<br>Alemania</p>`],
['Representada por',`<p>${legalMD}, director general (Geschäftsführer)</p>`],
['Contacto',`<p>Correo electrónico: ${legalMail}</p>`],
['Registro mercantil',`<p>Inscrita en el registro mercantil alemán (Handelsregister)<br>Tribunal de registro: Amtsgericht Walsrode<br>Número de registro: HRB 213510</p>`],
['Número de IVA',`<p>Número de identificación a efectos del IVA según el § 27a de la Ley alemana del IVA (UStG): DE461455043</p>`],
['Responsable del contenido según el § 18, apartado 2, MStV',`<p>${legalMD}, dirección indicada arriba</p>`]]}
},
datenschutz:{
de:{title:'Datenschutzerklärung',sections:[
['1. Verantwortlicher',`<p>${legalAddress}<br>Deutschland<br>E-Mail: ${legalMail}</p><p>Vertreten durch den Geschäftsführer ${legalMD}.</p>`],
['2. Überblick',`<p>Diese Website verwendet keine Cookies, keine Analyse- oder Trackingdienste und kein Kontaktformular. Personenbezogene Daten werden nur verarbeitet, soweit dies für die Bereitstellung der Website, die Darstellung der Inhalte oder die Beantwortung Ihrer Anfragen erforderlich ist.</p>`],
['3. Hosting',`<p>Die Website wird über GitHub Pages bereitgestellt. Anbieter ist ${legalGitHub}. Beim Aufruf der Website verarbeitet GitHub technisch notwendige Daten, insbesondere Ihre IP-Adresse, Datum und Uhrzeit des Abrufs, die aufgerufene Seite sowie Browser- und Systeminformationen, um die Seiten auszuliefern und die Sicherheit des Dienstes zu gewährleisten.</p><p>Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse liegt in einer zuverlässigen und sicheren Bereitstellung der Website. Dabei können Daten in die USA übermittelt werden. GitHub stützt solche Übermittlungen auf das EU-U.S. Data Privacy Framework (Angemessenheitsbeschluss nach Art. 45 DSGVO). Weitere Informationen: <a href="https://docs.github.com/de/site-policy/privacy-policies/github-general-privacy-statement" rel="noopener" target="_blank">Datenschutzerklärung von GitHub</a>.</p>`],
['4. Schriftarten',`<p>Die Schrift EB Garamond wird von unserem eigenen Webspace geladen (siehe Abschnitt 3); dabei werden keine Daten an weitere Dritte übermittelt. Für die übrigen Schriften nutzt die Website Adobe Fonts (${legalAdobe}). Beim Laden übermittelt Ihr Browser Ihre IP-Adresse an Server von Adobe; eine Übermittlung in die USA ist nicht ausgeschlossen. Adobe gibt an, für Web-Schriften keine Cookies zu setzen und die IP-Adresse nicht zu speichern.</p><p>Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse liegt in einer einheitlichen und gut lesbaren Darstellung. Adobe ist nach dem EU-U.S. Data Privacy Framework zertifiziert. Weitere Informationen: <a href="https://www.adobe.com/de/privacy/policies/adobe-fonts.html" rel="noopener" target="_blank">Adobe Fonts</a>.</p>`],
['5. Eingebettete Inhalte',`<p>Einzelne Seiten binden Inhalte externer Anbieter ein. Das Videoarchiv zeigt YouTube-Videos im erweiterten Datenschutzmodus (youtube-nocookie.com). Seiten der Zonneveld Manufactura zeigen Dokumente aus Google Drive bzw. Google Docs und verlinken auf Google Sites. Anbieter ist jeweils ${legalGoogle}.</p><p>Beim Aufruf einer solchen Seite stellt Ihr Browser eine Verbindung zu Servern von Google her und übermittelt dabei insbesondere Ihre IP-Adresse; beim Abspielen eines Videos können weitere Daten verarbeitet werden. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse liegt in der Darstellung dieser Inhalte. Google ist nach dem EU-U.S. Data Privacy Framework zertifiziert.</p>`],
['6. Speicherung im Browser',`<p>Wenn Sie eine Sprache auswählen, wird diese Auswahl im lokalen Speicher Ihres Browsers abgelegt (Schlüssel <code>ze-language</code>). Die Zeichenwerkzeuge der Zonneveld Manufactura speichern Ihre Einstellungen ebenfalls lokal (<code>petala-machine</code>, <code>petala-v1</code>). Diese Angaben verbleiben auf Ihrem Gerät und werden nicht an uns übermittelt. Die Speicherung ist für die von Ihnen gewünschte Funktion unbedingt erforderlich (§ 25 Abs. 2 Nr. 2 TDDDG). Sie können sie jederzeit über die Einstellungen Ihres Browsers löschen.</p>`],
['7. Kontakt per E-Mail',`<p>Wenn Sie uns per E-Mail schreiben, verarbeiten wir Ihre Angaben (insbesondere E-Mail-Adresse, Name und Inhalt der Nachricht), um Ihre Anfrage zu beantworten. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, soweit die Anfrage auf einen Vertrag zielt, im Übrigen Art. 6 Abs. 1 lit. f DSGVO. Unsere E-Mails werden über Google Workspace (${legalGoogle}) verarbeitet. Wir löschen die Daten, sobald sie nicht mehr erforderlich sind; gesetzliche Aufbewahrungspflichten bleiben unberührt.</p>`],
['8. Ihre Rechte',`<p>Sie haben das Recht auf Auskunft (Art. 15 DSGVO), Berichtigung (Art. 16), Löschung (Art. 17), Einschränkung der Verarbeitung (Art. 18) und Datenübertragbarkeit (Art. 20). Sie können einer Verarbeitung, die auf Art. 6 Abs. 1 lit. f DSGVO beruht, aus Gründen, die sich aus Ihrer besonderen Situation ergeben, jederzeit widersprechen (Art. 21). Wenden Sie sich dazu an ${legalMail}.</p><p>Sie haben außerdem das Recht, sich bei einer Datenschutz-Aufsichtsbehörde zu beschweren. Für uns zuständig ist:<br>${legalAuthority}</p>`],
['9. Stand',`<p>Oktober 2026</p>`]]},
en:{title:'Privacy policy',note:'This is a courtesy translation; the German version is legally binding.',sections:[
['1. Controller',`<p>${legalAddress}<br>Germany<br>Email: ${legalMail}</p><p>Represented by the Managing Director, ${legalMD}.</p>`],
['2. Overview',`<p>This website uses no cookies, no analytics or tracking services and no contact form. Personal data are processed only as far as necessary to provide the website, display its content or answer your enquiries.</p>`],
['3. Hosting',`<p>The website is served by GitHub Pages, provided by ${legalGitHub}. When you visit the website, GitHub processes technically necessary data, in particular your IP address, the date and time of the request, the page requested and browser and system information, in order to deliver the pages and keep the service secure.</p><p>The legal basis is Art. 6(1)(f) GDPR; our legitimate interest is the reliable and secure provision of the website. Data may be transferred to the USA. GitHub relies on the EU-U.S. Data Privacy Framework (adequacy decision under Art. 45 GDPR) for such transfers. More information: <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" rel="noopener" target="_blank">GitHub privacy statement</a>.</p>`],
['4. Fonts',`<p>The EB Garamond typeface is loaded from our own web space (see section 3); no data are passed to any further third party in the process. For the other typefaces, the website uses Adobe Fonts (${legalAdobe}). Your browser transmits your IP address to Adobe's servers; a transfer to the USA cannot be ruled out. Adobe states that it sets no cookies to serve web fonts and does not store the IP address.</p><p>The legal basis is Art. 6(1)(f) GDPR; our legitimate interest is consistent, legible presentation. Adobe is certified under the EU-U.S. Data Privacy Framework. More information: <a href="https://www.adobe.com/privacy/policies/adobe-fonts.html" rel="noopener" target="_blank">Adobe Fonts</a>.</p>`],
['5. Embedded content',`<p>Some pages embed content from external providers. The video archive shows YouTube videos in privacy-enhanced mode (youtube-nocookie.com). Zonneveld Manufactura pages show documents from Google Drive or Google Docs and link to Google Sites. The provider in each case is ${legalGoogle}.</p><p>When you open such a page, your browser connects to Google's servers and transmits, in particular, your IP address; further data may be processed when a video is played. The legal basis is Art. 6(1)(f) GDPR; our legitimate interest is presenting this content. Google is certified under the EU-U.S. Data Privacy Framework.</p>`],
['6. Storage in your browser',`<p>When you choose a language, the choice is kept in your browser's local storage (key <code>ze-language</code>). The drawing tools of Zonneveld Manufactura also keep your settings locally (<code>petala-machine</code>, <code>petala-v1</code>). This information stays on your device and is not sent to us. Storing it is strictly necessary for the function you requested (§ 25(2) no. 2 TDDDG). You can delete it at any time in your browser settings.</p>`],
['7. Contact by email',`<p>If you email us, we process the information you provide (in particular your email address, name and message) to answer your enquiry. The legal basis is Art. 6(1)(b) GDPR where the enquiry concerns a contract, and otherwise Art. 6(1)(f) GDPR. Our email is processed through Google Workspace (${legalGoogle}). We delete the data once they are no longer needed, subject to statutory retention obligations.</p>`],
['8. Your rights',`<p>You have the right of access (Art. 15 GDPR), rectification (Art. 16), erasure (Art. 17), restriction of processing (Art. 18) and data portability (Art. 20). You may object at any time, on grounds relating to your particular situation, to processing based on Art. 6(1)(f) GDPR (Art. 21). Please write to ${legalMail}.</p><p>You also have the right to lodge a complaint with a data protection supervisory authority. The authority responsible for us is:<br>${legalAuthority}</p>`],
['9. Last updated',`<p>October 2026</p>`]]},
pt:{title:'Política de privacidade',note:'Esta é uma tradução de cortesia; a versão em alemão é a juridicamente válida.',sections:[
['1. Responsável',`<p>${legalAddress}<br>Alemanha<br>E-mail: ${legalMail}</p><p>Representada pelo diretor-geral, ${legalMD}.</p>`],
['2. Visão geral',`<p>Este site não usa cookies, serviços de análise ou rastreamento, nem formulário de contato. Dados pessoais são tratados apenas na medida necessária para disponibilizar o site, exibir seu conteúdo ou responder às suas mensagens.</p>`],
['3. Hospedagem',`<p>O site é disponibilizado pelo GitHub Pages, serviço de ${legalGitHub}. Quando você acessa o site, o GitHub trata dados tecnicamente necessários, em especial seu endereço IP, data e hora do acesso, a página solicitada e informações do navegador e do sistema, para entregar as páginas e manter o serviço seguro.</p><p>A base legal é o art. 6.º, n.º 1, alínea f, do RGPD; nosso interesse legítimo é disponibilizar o site de forma confiável e segura. Os dados podem ser transferidos para os EUA. O GitHub fundamenta essas transferências no EU-U.S. Data Privacy Framework (decisão de adequação nos termos do art. 45.º do RGPD). Mais informações: <a href="https://docs.github.com/pt/site-policy/privacy-policies/github-general-privacy-statement" rel="noopener" target="_blank">declaração de privacidade do GitHub</a>.</p>`],
['4. Fontes tipográficas',`<p>A fonte EB Garamond é carregada do nosso próprio espaço de hospedagem (ver seção 3); nenhum dado é repassado a outros terceiros nesse processo. Para as demais fontes, o site usa o Adobe Fonts (${legalAdobe}). Seu navegador transmite seu endereço IP aos servidores da Adobe; não se pode excluir uma transferência para os EUA. A Adobe informa que não usa cookies para fornecer fontes web e não armazena o endereço IP.</p><p>A base legal é o art. 6.º, n.º 1, alínea f, do RGPD; nosso interesse legítimo é uma apresentação uniforme e legível. A Adobe é certificada no EU-U.S. Data Privacy Framework. Mais informações: <a href="https://www.adobe.com/privacy/policies/adobe-fonts.html" rel="noopener" target="_blank">Adobe Fonts</a>.</p>`],
['5. Conteúdo incorporado',`<p>Algumas páginas incorporam conteúdo de fornecedores externos. O acervo de vídeos mostra vídeos do YouTube no modo de privacidade aprimorada (youtube-nocookie.com). Páginas da Zonneveld Manufactura mostram documentos do Google Drive ou Google Docs e têm links para o Google Sites. O fornecedor, em todos os casos, é ${legalGoogle}.</p><p>Ao abrir uma dessas páginas, seu navegador se conecta a servidores do Google e transmite, em especial, seu endereço IP; ao reproduzir um vídeo, outros dados podem ser tratados. A base legal é o art. 6.º, n.º 1, alínea f, do RGPD; nosso interesse legítimo é apresentar esse conteúdo. O Google é certificado no EU-U.S. Data Privacy Framework.</p>`],
['6. Armazenamento no navegador',`<p>Quando você escolhe um idioma, a escolha fica guardada no armazenamento local do seu navegador (chave <code>ze-language</code>). As ferramentas de desenho da Zonneveld Manufactura também guardam suas configurações localmente (<code>petala-machine</code>, <code>petala-v1</code>). Essas informações ficam no seu dispositivo e não são enviadas a nós. O armazenamento é estritamente necessário para a função que você solicitou (§ 25, parágrafo 2, n.º 2, TDDDG). Você pode apagá-las a qualquer momento nas configurações do navegador.</p>`],
['7. Contato por e-mail',`<p>Se você nos escrever por e-mail, tratamos as informações enviadas (em especial endereço de e-mail, nome e conteúdo da mensagem) para responder. A base legal é o art. 6.º, n.º 1, alínea b, do RGPD quando a mensagem se refere a um contrato e, nos demais casos, a alínea f. Nossos e-mails são processados pelo Google Workspace (${legalGoogle}). Apagamos os dados quando deixam de ser necessários, ressalvadas as obrigações legais de conservação.</p>`],
['8. Seus direitos',`<p>Você tem direito de acesso (art. 15.º do RGPD), retificação (art. 16.º), apagamento (art. 17.º), limitação do tratamento (art. 18.º) e portabilidade (art. 20.º). Pode opor-se a qualquer momento, por motivos relacionados à sua situação particular, ao tratamento baseado no art. 6.º, n.º 1, alínea f (art. 21.º). Escreva para ${legalMail}.</p><p>Você também pode apresentar reclamação a uma autoridade de proteção de dados. A autoridade competente para nós é:<br>${legalAuthority}</p>`],
['9. Atualização',`<p>Outubro de 2026</p>`]]},
es:{title:'Política de privacidad',note:'Esta es una traducción de cortesía; la versión en alemán es la jurídicamente vinculante.',sections:[
['1. Responsable',`<p>${legalAddress}<br>Alemania<br>Correo electrónico: ${legalMail}</p><p>Representada por el director general, ${legalMD}.</p>`],
['2. Resumen',`<p>Este sitio no utiliza cookies, servicios de análisis o seguimiento ni formulario de contacto. Los datos personales se tratan solo en la medida necesaria para ofrecer el sitio, mostrar su contenido o responder a tus consultas.</p>`],
['3. Alojamiento',`<p>El sitio se ofrece a través de GitHub Pages, servicio de ${legalGitHub}. Cuando visitas el sitio, GitHub trata datos técnicamente necesarios, en particular tu dirección IP, la fecha y hora de la solicitud, la página solicitada e información del navegador y del sistema, para entregar las páginas y mantener la seguridad del servicio.</p><p>La base jurídica es el art. 6, apartado 1, letra f, del RGPD; nuestro interés legítimo es ofrecer el sitio de forma fiable y segura. Los datos pueden transferirse a EE. UU. GitHub basa estas transferencias en el EU-U.S. Data Privacy Framework (decisión de adecuación conforme al art. 45 del RGPD). Más información: <a href="https://docs.github.com/es/site-policy/privacy-policies/github-general-privacy-statement" rel="noopener" target="_blank">declaración de privacidad de GitHub</a>.</p>`],
['4. Tipografías',`<p>La tipografía EB Garamond se carga desde nuestro propio espacio de alojamiento (ver sección 3); en este proceso no se transmiten datos a otros terceros. Para las demás tipografías, el sitio utiliza Adobe Fonts (${legalAdobe}). Tu navegador transmite tu dirección IP a los servidores de Adobe; no se puede descartar una transferencia a EE. UU. Adobe indica que no utiliza cookies para servir tipografías web y que no almacena la dirección IP.</p><p>La base jurídica es el art. 6, apartado 1, letra f, del RGPD; nuestro interés legítimo es una presentación uniforme y legible. Adobe está certificada en el EU-U.S. Data Privacy Framework. Más información: <a href="https://www.adobe.com/privacy/policies/adobe-fonts.html" rel="noopener" target="_blank">Adobe Fonts</a>.</p>`],
['5. Contenido incrustado',`<p>Algunas páginas incrustan contenido de proveedores externos. El archivo de videos muestra videos de YouTube en modo de privacidad mejorada (youtube-nocookie.com). Las páginas de Zonneveld Manufactura muestran documentos de Google Drive o Google Docs y enlazan a Google Sites. El proveedor, en todos los casos, es ${legalGoogle}.</p><p>Al abrir una de estas páginas, tu navegador se conecta a servidores de Google y transmite, en particular, tu dirección IP; al reproducir un video pueden tratarse otros datos. La base jurídica es el art. 6, apartado 1, letra f, del RGPD; nuestro interés legítimo es mostrar este contenido. Google está certificado en el EU-U.S. Data Privacy Framework.</p>`],
['6. Almacenamiento en el navegador',`<p>Cuando eliges un idioma, la elección se guarda en el almacenamiento local de tu navegador (clave <code>ze-language</code>). Las herramientas de dibujo de Zonneveld Manufactura también guardan tus ajustes localmente (<code>petala-machine</code>, <code>petala-v1</code>). Esta información permanece en tu dispositivo y no se nos envía. El almacenamiento es estrictamente necesario para la función que solicitaste (§ 25, apartado 2, n.º 2, TDDDG). Puedes borrarla en cualquier momento desde la configuración del navegador.</p>`],
['7. Contacto por correo electrónico',`<p>Si nos escribes por correo electrónico, tratamos la información que nos envías (en particular dirección de correo, nombre y contenido del mensaje) para responderte. La base jurídica es el art. 6, apartado 1, letra b, del RGPD cuando la consulta se refiere a un contrato y, en los demás casos, la letra f. Nuestro correo se procesa a través de Google Workspace (${legalGoogle}). Borramos los datos cuando dejan de ser necesarios, sin perjuicio de las obligaciones legales de conservación.</p>`],
['8. Tus derechos',`<p>Tienes derecho de acceso (art. 15 del RGPD), rectificación (art. 16), supresión (art. 17), limitación del tratamiento (art. 18) y portabilidad (art. 20). Puedes oponerte en cualquier momento, por motivos relacionados con tu situación particular, al tratamiento basado en el art. 6, apartado 1, letra f (art. 21). Escríbenos a ${legalMail}.</p><p>También tienes derecho a presentar una reclamación ante una autoridad de protección de datos. La autoridad competente para nosotros es:<br>${legalAuthority}</p>`],
['9. Actualización',`<p>Octubre de 2026</p>`]]}
}};
function legalTitle(kind,l){return (legalCopy[kind]||legalCopy.impressum)[l].title}
function legalView(kind,l,t){const c=(legalCopy[kind]||legalCopy.impressum)[l];
return `<main id="main" class="legal wrap"><div class="legal-body"><p class="eyebrow">Zonneveld Engineering</p><h1>${c.title}</h1>${c.note?`<p class="legal-note">${c.note}</p>`:''}${c.sections.map(([h,b])=>`<section><h2>${h}</h2>${b}</section>`).join('')}</div></main>`;}
