/* SVG integration for Jim Bumgardner's MIT-licensed CDMS. */
let traces=[],lastTrace=null,count=0,latestSetup=null,limitReached=false;
function instance(){return window.Processing?.getInstanceById('CDMS')}
let feedbackUntil=0;
function tell(t){feedbackUntil=Date.now()+7000;const e=document.getElementById('status');if(e)e.textContent=t}
function saveBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
function jsClear(){traces=[];lastTrace=null;count=0;limitReached=false;tell('Papel limpo. Clique em Desenhar ou Ciclo completo.')}
// Liang–Barsky clipping: export exactly the portion on the 648 × 648 paper.
function clip(x0,y0,x1,y1){let lo=0,hi=1;const dx=x1-x0,dy=y1-y0,p=[-dx,dx,-dy,dy],q=[x0,648-x0,y0,648-y0];for(let i=0;i<4;i++){if(p[i]===0){if(q[i]<0)return null}else{const t=q[i]/p[i];if(p[i]<0)lo=Math.max(lo,t);else hi=Math.min(hi,t);if(lo>hi)return null}}return [x0+lo*dx,y0+lo*dy,x0+hi*dx,y0+hi*dy]}
function jsCapture(x0,y0,x1,y1,r,g,b,w){if(limitReached)return;if(![x0,y0,x1,y1].every(Number.isFinite))return;const c=clip(x0,y0,x1,y1);if(!c){lastTrace=null;return}if(count>=300000){limitReached=true;instance()?.issueCmd('pause','');tell('Limite de 300 mil segmentos atingido. Exporte ou limpe o papel para continuar.');return}const color=`rgb(${r},${g},${b})`;if(!lastTrace||lastTrace.color!==color||lastTrace.w!==w||Math.hypot(lastTrace.end[0]-c[0],lastTrace.end[1]-c[1])>0.001){lastTrace={color,w,points:[[c[0],c[1]]],end:[c[0],c[1]]};traces.push(lastTrace)}lastTrace.points.push([c[2],c[3]]);lastTrace.end=[c[2],c[3]];count++;}
function jsLoadSetups(s){try{const v=JSON.parse(localStorage.getItem('petala-machine')||'null');if(validSetup(v))Object.assign(s,v)}catch{}latestSetup=s}
function plainSetup(s){return {setupMode:Number(s.setupMode),penColorIdx:Number(s.penColorIdx),penWidthIdx:Number(s.penWidthIdx),setupTeeth:Array.from(s.setupTeeth,row=>Array.from(row,Number)),setupMounts:Array.from(s.setupMounts,row=>Array.from(row,Number)),setupPens:Array.from(s.setupPens,row=>Array.from(row,Number)),setupInversions:Array.from(s.setupInversions,row=>Array.from(row,Boolean))};}
function jsSaveSetups(s){latestSetup=plainSetup(s);try{localStorage.setItem('petala-machine',JSON.stringify(latestSetup))}catch{}}
function saveSetup(){try{const p=instance();if(!p){tell('Aguarde a máquina carregar.');return}p.doSaveSetup();if(!validSetup(latestSetup))throw Error('Montagem inválida');saveBlob(new Blob([JSON.stringify(latestSetup,null,2)],{type:'application/json'}),'maquina-montagem.json');tell('Montagem salva. Use Abrir montagem para restaurar seus parâmetros.');}catch(e){tell('Não foi possível salvar a montagem: '+e.message);}}
function validSetup(v){if(!v||!Number.isInteger(v.setupMode)||v.setupMode<0||v.setupMode>6||!Number.isInteger(v.penColorIdx)||v.penColorIdx<0||v.penColorIdx>4||!Number.isInteger(v.penWidthIdx)||v.penWidthIdx<0||v.penWidthIdx>5)return false;const lengths={setupTeeth:[2,4,5,3,3,3,7],setupMounts:[3,3,3,5,5,7,3],setupPens:[2,2,2,2,2,2,2],setupInversions:[1,1,1,2,2,3,1]};for(const [key,lens]of Object.entries(lengths)){if(!Array.isArray(v[key])||v[key].length!==7)return false;for(let i=0;i<7;i++){if(!Array.isArray(v[key][i])||v[key][i].length!==lens[i])return false;for(const x of v[key][i]){if(key==='setupInversions'){if(typeof x!=='boolean')return false}else if(typeof x!=='number'||!Number.isFinite(x)||Math.abs(x)>400)return false;if(key==='setupTeeth'&&(!Number.isInteger(x)||x<24||x>151))return false;}}}return true}
function buttonFeedback(){setTimeout(()=>{const p=instance();if(!p)return;document.querySelectorAll('[data-cmd="setup"]').forEach(b=>b.classList.toggle('active',Number(b.dataset.sub)===Number(p.getSetupMode())));},0)}
function setupButtons(){setTimeout(buttonFeedback,100)}
function mydebug(){}
function machineSvg(){if(!count){tell('Desenhe primeiro para exportar.');return null}let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const t of traces)for(const [x,y]of t.points){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}const size=Number(document.getElementById('size').value);if(!Number.isFinite(size)||size<10||size>500){tell('Escolha uma dimensão entre 10 e 500 mm.');return null}const extent=Math.max(maxX-minX,maxY-minY)||1;const pad=traces.reduce((m,t)=>Math.max(m,t.w),0);const width=maxX-minX+pad,height=maxY-minY+pad;return `<svg xmlns="http://www.w3.org/2000/svg" width="${width/extent*size}mm" height="${height/extent*size}mm" viewBox="${minX-pad/2} ${minY-pad/2} ${width} ${height}"><title>Desenho cicloide</title>${traces.map(t=>`<path fill="none" stroke="${t.color}" stroke-width="${t.w}" stroke-linecap="round" stroke-linejoin="round" d="${t.points.map(([x,y],i)=>(i?'L':'M')+x.toFixed(3)+' '+y.toFixed(3)).join(' ')}"/>`).join('')}</svg>`}
function exportSvg(){const s=machineSvg();if(s){saveBlob(new Blob([s],{type:'image/svg+xml'}),'maquina-cicloide.svg');tell('SVG exportado. Para caneta, escolha Desenhar no Design Space.')}}
function makeSnapshot(){const s=machineSvg();if(!s)return;const u=URL.createObjectURL(new Blob([s],{type:'image/svg+xml'})),img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=2400;c.height=Math.round(2400*img.height/img.width);c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{if(b)saveBlob(b,'maquina-cicloide.png')});URL.revokeObjectURL(u)};img.onerror=()=>{URL.revokeObjectURL(u);tell('Não foi possível gerar a imagem.')};img.src=u}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.type==='export-svg')exportSvg();else if(e.data?.type==='save-project')document.getElementById('save').click();else if(e.data?.type==='open-project')document.getElementById('open').click();else if(e.data?.type==='apply-setup'){const p=instance();if(p&&validSetup(e.data.setup)){localStorage.setItem('petala-machine',JSON.stringify(plainSetup(e.data.setup)));p.issueCmd('pause','');p.doLoadSetup();p.drawingSetup(e.data.setup.setupMode,true);buttonFeedback();tell('Montagem da busca aplicada. Clique em Ciclo completo.');}}else if(e.data?.type==='pause')instance()?.issueCmd('pause','')});
window.addEventListener('DOMContentLoaded',()=>{
 document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>{if(limitReached&&['play','ff','fff','rr','rrr'].includes(b.dataset.cmd)){tell('Exporte e limpe o papel para continuar.');return}instance()?.issueCmd(b.dataset.cmd,b.dataset.sub||'');buttonFeedback()});
 document.querySelectorAll('[data-nudge]').forEach(b=>b.onclick=()=>{const code=Number(b.dataset.nudge);instance()?.nudge(code===38||code===39?1:-1,code)});
 document.getElementById('nine').onclick=()=>{const p=instance();if(!p)return;p.applyNineLobes();tell('Exemplo G com 9 lóbulos aplicado. Clique em Ciclo completo (100 voltas da mesa).');};
 document.getElementById('invert').onclick=()=>instance()?.invertConnectingRod();document.getElementById('color').onclick=()=>instance()?.advancePenColor(1);document.getElementById('thin').onclick=()=>instance()?.advancePenWidth(-1);document.getElementById('thick').onclick=()=>instance()?.advancePenWidth(1);document.getElementById('svg').onclick=exportSvg;document.getElementById('png').onclick=makeSnapshot;
 document.getElementById('save').onclick=saveSetup;document.getElementById('open').onclick=()=>document.getElementById('file').click();document.getElementById('file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>50000)throw Error();const v=JSON.parse(await f.text());if(!validSetup(v))throw Error();localStorage.setItem('petala-machine',JSON.stringify(v));instance()?.issueCmd('pause','');instance()?.doLoadSetup();instance()?.drawingSetup(v.setupMode,true);buttonFeedback();tell('Montagem aberta.')}catch{tell('Arquivo de montagem inválido.')}e.target.value=''};
 let n=0;const timer=setInterval(()=>{if(instance()){clearInterval(timer);tell('Pronto. Escolha uma montagem e clique em Ciclo completo.')}else if(++n>60){clearInterval(timer);tell('A máquina não carregou. Recarregue a página para tentar novamente.')}},500);
 setInterval(()=>{if(count&&!limitReached&&Date.now()>feedbackUntil)tell(`${count.toLocaleString('pt-BR')} segmentos · ${instance()?.getIsMoving()?'desenhando…':'pausado · pronto para exportar'}`)},1000);
});
