import {loadCatalogueOrder,bookCatalogue,catalogueOrders} from './collection.mjs?v=a24c21ddc48f';
import {mountExportPage,setupSelection} from './export-page.mjs?v=a24c21ddc48f';
import {alternatives,shortPiece,mergeCatalogue,patternId,addRecipes} from './catalogue.mjs?v=a24c21ddc48f';
import {materialize,materializeCode} from './recipes.mjs?v=a24c21ddc48f';
import {setupArchive} from './archive.mjs?v=a24c21ddc48f';
import {setupPDF} from './pdf-ui.mjs?v=a24c21ddc48f';
import {attachHelp} from './help.mjs?v=a24c21ddc48f';
import {localMode,exportHistory,importHistory,discoveryRows,discoveryOrders,catalogueUpdated,recipeItems} from './storage.mjs?v=a24c21ddc48f';
import {mountGeneratorPage} from './forge-page.mjs?v=a24c21ddc48f';
import {localize,translateMarkup,userError} from './i18n.mjs?v=a24c21ddc48f';
import {setupLab} from './lab-ui.mjs?v=a24c21ddc48f';
import {setupSearch,selectSearchItem} from './search-ui.mjs?v=a24c21ddc48f';
import{patchSVG,tileSVG,polygon,bounds,path,grid}from'./geometry.mjs?v=a24c21ddc48f';
const $=id=>document.getElementById(id),labels={'reid-computed':'Reconstrução geométrica',reid:'Robert Reid',tileable:'Com tesselação',experimental:'Peça construída',generated:'Descoberta salva',all:'Todas as peças',list:'Catálogo geral',trans:'Translação',rot:'Rotação 180°',iso:'Isoédrica',aniso:'Anisoédrica',nontile:'Não tessela',holes:'Com furos',...Object.fromEntries(Array.from({length:6},(_,i)=>[`${i+1}-morphic`,`${i+1}-morphic · ${i+1} ${i?'padrões':'padrão'}`]))},help={reid:'Prototiles identificados no livro de Robert Reid. A referência do livro não implica que as alternativas do catálogo reproduzam aquele desenho.',all:'Escolha uma peça para explorar os padrões documentados.',trans:'Repetição apenas por translações.',rot:'Repetição por translações e rotações de 180°.',iso:'As simetrias da tesselação levam qualquer peça a qualquer outra.',aniso:'A peça tessela o plano, mas não admite tesselação isoédrica.',holes:'Peças com regiões vazias internas, preservadas no desenho.',nontile:'Estas peças não preenchem o plano. O prototile continua disponível para exportação.'};
let discoveries=[],summary=[],items=[],filtered=[],selected=null,page=0,svg='',request=0;const size=24,cache=new Map(),baseTilings=new WeakMap();
function option(value,label){const o=document.createElement('option');o.value=value;o.textContent=label;return o}
function status(s,error=false){$('status').textContent=s;$('status').classList.toggle('error',error)}
async function fetchJSON(url){const r=await fetch(new URL(url,import.meta.url));if(!r.ok)throw Error('Não foi possível carregar os dados. Recarregue a página.');return r.json()}
// Carrega só a ordem visível; a lista de ordens vem do índice publicado e do histórico local.
async function refreshDiscoveries(n=+$('order').value){const chosen=$('order').value;for(const k of await catalogueOrders(await discoveryOrders())){if(![...$('order').options].some(o=>+o.value===k))$('order').append(option(k,`${k} △`))}if(chosen)$('order').value=chosen;discoveries=n?await discoveryRows(n):[]}
async function loadOrder({query=''}={}){const token=++request,n=+$('order').value;document.body.classList.add('loading');$('export').disabled=true;try{await refreshDiscoveries(n);if(!cache.has(n))cache.set(n,await loadCatalogueOrder(n));if(token!==request)return;items=addRecipes(mergeCatalogue(cache.get(n),discoveries,n),await recipeItems(n));if(token!==request)return;arrange();const cats={};for(const x of items)for(const c of x.categories)cats[c]=(cats[c]||0)+1;$('category').replaceChildren(option('tileable','Com tesselação'),option('all','Todas as peças'),...Object.keys(labels).filter(k=>cats[k]&&k!=='list').map(k=>option(k,`${labels[k]} (${cats[k]})`)));$('find').value=query;$('coverage').textContent=n<=13?'Catálogo completo desta ordem.':'Seleção disponível na coleção. Esta ordem não tem listagem completa.';filter(true)}catch(e){status(userError(e),true)}finally{if(token===request)document.body.classList.remove('loading')}}
// Peças do gerador publicadas como receita ainda sem contorno: usam as medidas guardadas.
const perim=x=>x.code?x.code.length:x.meta.perimeter;
function metric(x){if(!x.code)return x.meta.box;const p=polygon(x.code),a=p.map(p=>p[0]),b=p.map(p=>p[1]);return(Math.max(...a)-Math.min(...a))*(Math.max(...b)-Math.min(...b))}
function arrange(){items=[...items].sort((a,b)=>($('sort').value==='compact'?metric(a)-metric(b)||perim(a)-perim(b):perim(a)-perim(b)||metric(a)-metric(b))||a.id.localeCompare(b.id));items.forEach((x,i)=>x.rank=i+1)}
function filter(reset=false){const cat=$('category').value,q=$('find').value.trim().toLowerCase().split(/\s*\/\s*|\s+T-/i)[0];filtered=items.filter(x=>(cat==='all'||cat==='tileable'&&(x.tilings.length>0||x.lazy)||x.categories.includes(cat))&&(!q||(/^\d+$/.test(q)?x.rank===Number(q):x.id.toLowerCase().includes(q))));filtered.sort((a,b)=>a.rank-b.rank);page=0;$('category-help').textContent=help[cat]||(cat==='tileable'?'Peças com tesselação documentada ou descoberta salva.':null)||'Uma peça k-morphic admite exatamente k tesselações, segundo a classificação da fonte.';$('result-count').textContent=filtered.length===1?'1 peça':`${filtered.length.toLocaleString('pt-BR')} peças`;renderCards();if(reset||!filtered.includes(selected)){if(filtered.length)choose(filtered[0]);else{selected=null;selectSearchItem(null);$('prototype').innerHTML='';$('patch').innerHTML='<div class="empty">Nenhuma peça corresponde a este número.</div>';$('piece-title').textContent='Nenhuma peça';$('badges').replaceChildren();$('tiling').replaceChildren();$('source').textContent='';$('patch-note').textContent='';$('triangle-count').textContent='';$('export').disabled=true;$('export-tile').disabled=true;svg=''}}}
function renderCards(){const part=filtered.slice(page*size,(page+1)*size);$('tiles').replaceChildren(...part.map(x=>{const b=document.createElement('button');b.className='tile'+(x===selected?' selected':'');b.setAttribute('aria-label',`${x.id}, ${x.n} triângulos`);b.setAttribute('aria-pressed',String(x===selected));b.innerHTML=(x.code?tileSVG(x.code,{thumb:true}):'<svg viewBox="0 0 10 10" aria-hidden="true"></svg>')+`<span>${x.rank||x.id.slice(-6)}</span>`;b.onclick=()=>choose(x);return b}));drawLazy(part);$('page').textContent=`${filtered.length?page+1:0} / ${Math.ceil(filtered.length/size)}`;$('prev').disabled=page===0;$('next').disabled=(page+1)*size>=filtered.length;setupSelection()}
// Desenha as miniaturas das receitas visíveis aos poucos, sem travar a página.
let drawing=0;function drawLazy(part){const todo=part.filter(x=>x.lazy&&!x.code);if(!todo.length)return;const ticket=++drawing;(async()=>{for(const x of todo){if(ticket!==drawing)return;try{materializeCode(x)}catch{continue}const b=[...$('tiles').children].find(b=>b.getAttribute('aria-label')?.startsWith(x.id+','));if(b)b.querySelector('svg').outerHTML=tileSVG(x.code,{thumb:true});await new Promise(r=>setTimeout(r,0))}})()}
function choose(x){if(x.lazy&&!x.tilings.length){selected=x;$('piece-title').textContent=`${shortPiece(x.id)} · ${x.n} △`;status('Reconstruindo a peça a partir da receita…');materialize(x).then(()=>{status('');if(selected===x)choose(x)}).catch(e=>status(userError(e),true));return}selected=x;$('piece-title').textContent=x.rank?`${shortPiece(x.id)} · ${x.n} △`:`${shortPiece(x.id)} · ${x.n} △`;$('triangle-count').textContent=`${x.n} △`;$('prototype').innerHTML=tileSVG(x.code);$('badges').replaceChildren(...x.categories.filter(c=>c!=='list').map(c=>{const s=document.createElement('span');s.className='badge';s.textContent=labels[c]||c;if(c.includes('morphic')){const q=document.createElement('button');q.className='question';q.dataset.help='morphic';q.textContent='?';q.setAttribute('aria-label','Explicar k-morphic');s.append(q)}return s}));$('export-tile').disabled=false;
 if(!baseTilings.has(x))baseTilings.set(x,x.tilings.slice());
 refreshTilingOptions();renderCards();renderPatch();selectSearchItem(x)}
function refreshTilingOptions(target){const x=selected;if(!x)return;const hasMorphic=x.tilings.some(t=>t.category.includes('morphic'));const indices=x.tilings.map((t,i)=>i).filter(i=>!hasMorphic||x.tilings[i].category.includes('morphic')||x.tilings[i].category==='generated');
 $('tiling').replaceChildren(...indices.map((i,j)=>{const t=x.tilings[i];return option(i,t.category==='generated'?`Descoberta ${t.fingerprint.slice(0,8)}`:`Padrão ${j+1} · ${labels[t.category]||'Tesselação'}`)}));if(!indices.length)$('tiling').append(option('','Sem tesselação documentada'));$('tiling').disabled=!indices.length;if(target){const index=x.tilings.findIndex(t=>t.fingerprint===target);if(index>=0)$('tiling').value=index}}
setupLab(async x=>{await refreshDiscoveries(x.n);$('order').value=x.n;await loadOrder();choose(items.find(i=>i.id===x.id)||x);$('piece-title').scrollIntoView({block:'start',behavior:'smooth'})});
setupSearch((entries,target,pieceId)=>{if(selected?.id!==pieceId)return;const previous=selected.tilings[+$('tiling').value]?.fingerprint;selected.tilings=[...baseTilings.get(selected).filter(t=>!t.fingerprint||!entries.some(e=>e.fingerprint===t.fingerprint)),...entries.map(e=>({...e.tiling,fingerprint:e.fingerprint,createdAt:e.createdAt,published:e.published}))];refreshTilingOptions(target||previous);renderPatch()});
function settings(){const width=+$('width').value,height=+$('height').value,unit=+$('unit').value;for(const id of['width','height','unit'])if(!$(id).checkValidity()||!$(id).value)throw Error('Informe dimensões válidas: patch de 10–1.000 mm e lado de 2–100 mm.');if(width*height/(unit*unit)>12000)throw Error('Este patch é muito denso. Aumente o lado do triângulo ou reduza a área.');return{width,height,unit,palette:$('palette').value,gridWidth:+$('grid-width').value,outline:Math.max(.35,+$('grid-width').value*2.5),title:selected.id,corners:$('color-corners').checked}}
function renderPatch(){if(!selected)return;svg='';$('export').disabled=true;try{const cfg=settings(),t=selected.tilings[+$('tiling').value];$('pattern-ref').textContent='';$('patch-size').textContent=`${cfg.width} × ${cfg.height} mm`;if(!t){$('patch').innerHTML=patchSVG(null,cfg).svg;const note=selected.categories.includes('nontile')?'Esta peça não tessela o plano, segundo a fonte.':'Não há tesselação documentada para esta peça nos arquivos.';$('patch-note').textContent=note;$('source').textContent=selected.sources.map(s=>`${s.file}, p. ${s.page}, fig. ${s.figure}`).join(' · ');status('A peça pode ser exportada individualmente.');return}patternId(t).then(id=>{if(selected?.tilings[+$('tiling').value]===t)$('pattern-ref').textContent=`${shortPiece(selected.id)} / T-${id.slice(0,20)}`});const result=patchSVG(t,cfg);svg=result.svg;$('patch').innerHTML=svg;$('source').textContent=t.category==='generated'?`${t.published?'Base publicada':'Histórico neste navegador'} · ${t.fingerprint.slice(0,12)} · ${new Date(t.createdAt).toLocaleString('pt-BR')}`:`${t.source.file} · página ${t.source.page} · figura ${t.source.figure}`;$('patch-note').textContent=`${result.count.toLocaleString('pt-BR')} peças intersectam o patch · ${result.colorCount} cores sem vizinhos iguais · recorte nas bordas · malha sempre visível`;$('export').disabled=false;status('')}catch(e){$('patch').innerHTML='<div class="empty">Ajuste as dimensões para gerar o patch.</div>';$('patch-note').textContent='';status(userError(e),true)}}
function download(text,name){text=translateMarkup(text);const a=document.createElement('a'),url=URL.createObjectURL(new Blob(['<?xml version="1.0" encoding="UTF-8"?>\n',text],{type:'image/svg+xml;charset=utf-8'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('SVG exportado. Abra no Illustrator e desagrupe para editar as peças, a malha e os contornos.')}
$('export').onclick=()=>{if(svg&&selected)download(svg,`${selected.id}-padrao-${+$('tiling').value+1}-${$('width').value}x${$('height').value}mm.svg`)};
$('export-tile').onclick=()=>{if(!selected)return;try{const {unit,gridWidth}=settings(),[x,y,r,b]=bounds(selected.code,unit),pad=unit/2,w=r-x+2*pad,h=b-y+2*pad;const s=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}mm" height="${h}mm" viewBox="${x-pad} ${y-pad} ${w} ${h}"><title>${selected.id}</title><g id="peca"><path d="${path(selected.code,0,0,unit)}" fill="#a6c1f0" fill-rule="evenodd"/></g><g id="malha-triangular"><path d="${grid(x-pad,y-pad,w,h,unit)}" fill="none" stroke="#526784" stroke-width="${gridWidth}"/></g><g id="contorno"><path d="${path(selected.code,0,0,unit)}" fill="none" stroke="#1c3871" stroke-width="0.3"/></g></svg>`;download(s,`${selected.id}-prototile.svg`)}catch(e){status(userError(e),true)}};
$('sort').onchange=()=>{arrange();filter();if(selected)choose(selected)};$('order').onchange=loadOrder;$('category').onchange=()=>filter();$('find').oninput=lookup;$('prev').onclick=()=>{page--;renderCards()};$('next').onclick=()=>{page++;renderCards()};for(const id of['tiling','width','height','unit','palette','grid-width','color-corners'])$(id).addEventListener('input',renderPatch);$('about').onclick=()=>$('info').showModal();$('close-info').onclick=()=>$('info').close();
try{summary=await fetchJSON('data/summary.json?v=a24c21ddc48f');const total=summary.reduce((s,x)=>s+x.count,0);$('total').textContent=total.toLocaleString('pt-BR');$('order').replaceChildren(...summary.map(x=>option(x.n,`${x.n} triângulo${x.n>1?'s':''} · ${x.count.toLocaleString('pt-BR')} ${x.count===1?'peça':'peças'}`)));$('order').value='19';$('collection-stats').textContent=`${total.toLocaleString('pt-BR')} peças distintas, ${summary.reduce((s,x)=>s+x.tilings,0).toLocaleString('pt-BR')} registros de tesselações e 21 ordens. As listagens gerais e polimórficas podem documentar o mesmo padrão; os registros de origem são mantidos.`;await loadOrder()}catch(e){status(userError(e),true);$('total').textContent='Erro no carregamento'}

export function refreshLanguage(){localize(document.querySelector('#polyiamonds-app')||document.body);attachHelp()}
refreshLanguage();
if(localMode()){document.querySelector('#local-history').hidden=false;$('backup-save').onclick=async()=>{try{const text=await exportHistory(),a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.href=url;a.download='polyiamonds-history.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Backup exportado.')}catch(e){status(userError(e),true)}};$('backup-open').onclick=()=>$('backup-file').click();$('backup-file').onchange=async()=>{try{const file=$('backup-file').files[0];if(!file)return;if(file.size>64000000)throw Error('Backup muito grande. Limite de 64 MB.');const count=await importHistory(await file.text());status(`${count} registros importados. O histórico foi atualizado.`);await loadOrder();$('lab-n').dispatchEvent(new Event('change'))}catch(e){status(e instanceof SyntaxError?'Não foi possível abrir este arquivo JSON.':userError(e),true)}$('backup-file').value=''}}

let lookupSerial=0;
async function lookup(){const ticket=++lookupSerial,q=$('find').value.trim(),match=q.match(/^(P(\d{2})-\d{5}|[LR](\d{3})-[a-f0-9]{8,64})(?:\s*(?:\/\s*)?T-([a-f0-9]{8,64}))?$/i);if(!match){filter();return}const n=+(match[2]||match[3]);await refreshDiscoveries(n);if(ticket!==lookupSerial)return;if(![...$('order').options].some(o=>+o.value===n)){status('Código não encontrado nesta base.',true);return}if(+$('order').value!==n){$('order').value=n;await loadOrder({query:q})}if(ticket!==lookupSerial)return;$('category').value='all';filter();const q1=match[1].toLowerCase(),matches=items.filter(x=>{const id=x.id.toLowerCase();return id.startsWith(q1)||(id.length===25&&q1.startsWith(id))});if(matches.length!==1){status('Código não encontrado nesta base.',true);return}const x=matches[0];choose(x);if(match[4]){const aa=await alternatives(x);if(ticket!==lookupSerial||selected!==x)return;const found=aa.filter(a=>a.id.startsWith(match[4].toLowerCase()));if(found.length!==1){status('Código não encontrado nesta base.',true);return}const i=x.tilings.indexOf(found[0].tiling);if(![...$('tiling').options].some(o=>+o.value===i))$('tiling').append(option(i,found[0].ref));$('tiling').value=i;renderPatch()}}
setupArchive();
setupPDF(()=>({selected,filtered,discoveries,gridWidth:+$('grid-width').value}));

globalThis.addEventListener('polyiamonds-history',()=>refreshDiscoveries().catch(e=>status(userError(e),true)));

await mountExportPage();
await mountGeneratorPage();
// Rodapé com a data da última incorporação ao catálogo publicado (aaaa mm dd).
catalogueUpdated().then(d=>{if(!d)return;const root=document.querySelector('#polyiamonds-app')||document.querySelector('main')?.parentElement||document.body;let p=root.querySelector('.catalog-updated');if(!p){p=document.createElement('p');p.className='catalog-updated';root.append(p)}p.textContent=`Última atualização: ${d.replaceAll('-',' ')}`}).catch(()=>{});
if(new URLSearchParams(location.search).has('find')){$('find').value=new URLSearchParams(location.search).get('find');await lookup()}
