// Subpágina ?view=generator: gerador de peças por tempo determinado, com contagem regressiva.
import{localize,translate,userError}from'./i18n.mjs?v=a24c21ddc48f';
import{localMode,discoveryRows,insertGenerated,recipeItems}from'./storage.mjs?v=a24c21ddc48f';
import{GENERATOR}from'./forge-core.mjs?v=a24c21ddc48f';
import{bookCatalogue}from'./collection.mjs?v=a24c21ddc48f';
import{shapeKey}from'./lab-core.mjs?v=a24c21ddc48f';
import{sha}from'./catalogue.mjs?v=a24c21ddc48f';
import{tileSVG,patchSVG}from'./geometry.mjs?v=a24c21ddc48f';
import{familiesFor,SYMMETRIES}from'./forge-core.mjs?v=a24c21ddc48f';
const $=id=>document.getElementById(id);
const TIMES=[[30,'30 segundos'],[60,'1 minuto'],[300,'5 minutos'],[900,'15 minutos'],[1800,'30 minutos'],[3600,'1 hora'],[14400,'4 horas'],[28800,'8 horas'],[43200,'12 horas']];
const fmt=n=>n.toLocaleString('pt-BR');
const clock=ms=>{const s=Math.max(0,Math.ceil(ms/1000));return[Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(x=>String(x).padStart(2,'0')).join(':')};
// A pasta escolhida fica lembrada em um banco separado do histórico de peças.
function settingsDB(){return new Promise((resolve,reject)=>{const q=indexedDB.open('zonneveld-polyiamonds-settings',1);q.onupgradeneeded=()=>q.result.createObjectStore('kv');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function setting(key,value){const d=await settingsDB();return new Promise((resolve,reject)=>{const tx=d.transaction('kv',value===undefined?'readonly':'readwrite'),s=tx.objectStore('kv'),q=value===undefined?s.get(key):s.put(value,key);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
export async function mountGeneratorPage(){if(new URLSearchParams(location.search).get('view')!=='generator')return;
 const root=document.querySelector('#polyiamonds-app')||document.body;root.dataset.view='generator';(document.querySelector('.poly-layout')||(!document.querySelector('#polyiamonds-app')&&document.querySelector('main')))?.setAttribute('hidden','');
 const cores=Math.max(1,Math.min(16,navigator.hardwareConcurrency||4)),host=document.createElement('section');host.id='generator-page';
 host.innerHTML=`<nav class="export-nav"><a href="?">Explorador</a><a href="?view=gallery">Galeria da base</a><a href="?view=export">Exportação</a><a href="?view=generator" aria-current="page">Gerador de peças</a></nav>
<h2>Gerador de peças</h2><p>Gera peças novas que tesselam o plano, durante o tempo escolhido, neste computador. Não pausa a cada descoberta: cada peça é validada e salva automaticamente. Ao final, o gerador para sozinho.</p>
<div class="gen-layout"><div class="panel gen-controls">
<div class="gen-grid"><div><label for="gen-time">Tempo de processamento</label><select id="gen-time">${TIMES.map(([v,t])=>`<option value="${v}"${v===1800?' selected':''}>${t}</option>`).join('')}</select></div>
<div><label for="gen-min">Triângulos por peça: de</label><input id="gen-min" type="number" min="22" max="200" step="1" value="95"></div><div><label for="gen-max">até</label><input id="gen-max" type="number" min="22" max="200" step="1" value="95"></div>
<div><label for="gen-style">Estilo das peças</label><select id="gen-style"><option value="interlock">Encaixe com braços</option><option value="compact">Formas compactas</option><option value="free">Livre</option></select></div>
<div><label for="gen-symmetry">Simetria do mosaico</label><select id="gen-symmetry"><option value="varied">Variada</option><option value="multi">Três ou mais orientações</option><option value="half">Somente meia-volta (180°)</option></select><p id="gen-families" class="help"></p></div>
<div><label for="gen-pick">Rigor da seleção</label><select id="gen-pick"><option value="10">Melhor de cada 10 peças válidas</option><option value="100" selected>Melhor de cada 100 peças válidas</option><option value="1000">Melhor de cada 1.000 peças válidas</option></select></div>
<div><label for="gen-cores">Núcleos do processador</label><select id="gen-cores">${Array.from({length:cores},(_,i)=>`<option value="${i+1}"${i+1===Math.max(1,Math.floor(cores/2))?' selected':''}>${i+1}</option>`).join('')}</select></div></div>
<label class="check"><input id="gen-wake" type="checkbox" checked> Manter a tela ligada durante a geração</label>
<div class="gen-clock-row"><output id="gen-clock" class="gen-clock" aria-live="off">00:30:00</output><progress id="gen-progress" max="1" value="0"></progress></div>
<div class="export-actions"><button id="gen-start" class="primary">Iniciar</button><button id="gen-pause" hidden>Pausar</button><button id="gen-cancel" hidden>Cancelar</button></div>
<p id="gen-status" class="help" role="status" aria-live="polite">Pronto. Escolha o tempo e clique em Iniciar.</p>
<div class="gen-folder"><h3>Arquivo para a próxima atualização do site</h3><p class="help">Vincule a pasta 183 Website/Ferramentas/Polyiamonds/DiscoveriesInbox. O arquivo desta sessão é gravado ali a cada minuto e ao final. Na próxima atualização do site, as peças são validadas e incorporadas ao catálogo publicado.</p><p class="help">O arquivo guarda só a receita de cada peça (semente da sessão e número da tentativa), poucos bytes por peça. O site redesenha as peças quando elas são exibidas ou exportadas.</p><button id="gen-folder">Vincular pasta DiscoveriesInbox</button> <button id="gen-download" disabled>Baixar JSON desta sessão</button><p id="gen-folder-status" class="help" role="status"></p></div>
</div><div class="panel gen-results"><h3>Última peça encontrada</h3><div id="gen-latest" class="gen-latest"><div class="empty">As peças aparecem aqui durante a geração.</div></div><p id="gen-latest-ref" class="help"></p><h3>Peças desta sessão <span id="gen-count" class="tag">0</span></h3><div id="gen-list" class="lab-results"></div></div></div>
<p class="search-footnote">Cada peça é um domínio fundamental de um grupo de simetria (p2, pg, pgg, p3, p6 ou p31m): as cópias cobrem o plano sem lacunas nem sobreposições, e a tesselação é validada antes de salvar. Explora famílias isoédricas, não todas as formas possíveis. Algumas ordens não admitem certas simetrias; por exemplo, 95 triângulos aceitam p2, pg e pgg. A seleção visual é uma heurística: braços largos, poucos dentes, pouca elongação e mais orientações. Novidade significa forma inédita nesta base. O tempo conta só enquanto a geração está ativa. Mantenha esta aba aberta; se o computador dormir, o cálculo para e continua quando ele acordar.</p>`;
 root.append(host);localize(root);
 if(!localMode()){$('gen-start').disabled=true;$('gen-status').textContent='O gerador por tempo está disponível na versão do site publicada no GitHub Pages.';return}
 let workers=[],state='idle',remaining=0,total=0,lastTick=0,timer=null,known=new Set(),queue=[],flushing=null,session=[],pieces=[],recipe=null,sessionName='',dir=null,dirty=false,lastWrite=0,wake=null,stats=new Map(),latestShown=0;
 const saved=()=>session.length,examined=()=>[...stats.values()].reduce((s,x)=>s+x,0);
 function controls(){const on=state==='running'||state==='paused';$('gen-start').hidden=on;$('gen-pause').hidden=!on;$('gen-cancel').hidden=!on;$('gen-pause').textContent=state==='paused'?'Retomar':'Pausar';for(const id of['gen-time','gen-min','gen-max','gen-style','gen-symmetry','gen-pick','gen-cores'])$(id).disabled=on;$('gen-download').disabled=!session.length}
 function showClock(){$('gen-clock').textContent=clock(state==='idle'?+$('gen-time').value*1000:remaining);$('gen-progress').value=total?1-remaining/total:0}
 function status(){if(state==='running')$('gen-status').textContent=`Gerando neste computador · ${fmt(saved())} peças novas salvas · ${fmt(examined())} formas examinadas`;else if(state==='paused')$('gen-status').textContent='Pausado. O tempo restante foi preservado; mantenha esta aba aberta.'}
 async function keepAwake(){try{if($('gen-wake').checked&&state==='running'&&document.visibilityState==='visible'&&navigator.wakeLock&&!wake){wake=await navigator.wakeLock.request('screen');wake.addEventListener('release',()=>{wake=null})}}catch{wake=null}}
 function releaseWake(){wake?.release().catch(()=>{});wake=null}
 document.addEventListener('visibilitychange',keepAwake);
 addEventListener('beforeunload',e=>{if(state==='running'||state==='paused'){e.preventDefault();e.returnValue=''}});
 // Pasta DiscoveriesInbox: lembrada entre visitas; a permissão é pedida no clique.
 const folderSupported=!!globalThis.showDirectoryPicker;if(!folderSupported){$('gen-folder').hidden=true;$('gen-folder-status').textContent='Este navegador não permite vincular pastas. Use Baixar JSON desta sessão ao final.'}
 else setting('inbox').then(h=>{if(h&&!dir){dir=h;$('gen-folder-status').textContent=`Pasta lembrada: ${h.name}. A autorização será pedida ao iniciar.`}}).catch(()=>{});
 async function authorize(){if(!dir)return false;try{if(await dir.queryPermission({mode:'readwrite'})==='granted')return true;return await dir.requestPermission({mode:'readwrite'})==='granted'}catch{return false}}
 $('gen-folder').onclick=async()=>{try{dir=await showDirectoryPicker({id:'polyiamonds-discoveries',mode:'readwrite'});await setting('inbox',dir).catch(()=>{});$('gen-folder-status').textContent=`Pasta vinculada: ${dir.name}. O arquivo desta sessão é atualizado a cada minuto.`;if(session.length){dirty=true;writeFolder()}}catch(e){if(e.name!=='AbortError')$('gen-folder-status').textContent=userError(e)}};
 // Arquivo da sessão: só a receita (semente + ajustes) e o número de cada tentativa escolhida.
 const fileText=()=>JSON.stringify({format:'zonneveld-polyiamonds-recipes',version:1,generator:GENERATOR,session:recipe,pieces});
 let writing=Promise.resolve();
 function writeFolder(){writing=writing.then(async()=>{if(!dir||!dirty||!recipe)return;if(await dir.queryPermission({mode:'readwrite'})!=='granted')throw Error('permission');dirty=false;const name=`${sessionName}.json`,count=pieces.length;const f=await dir.getFileHandle(name,{create:true}),w=await f.createWritable();try{await w.write(fileText());await w.close()}catch(e){await w.abort().catch(()=>{});throw e}lastWrite=Date.now();$('gen-folder-status').textContent=`Arquivo atualizado: ${name} (${fmt(count)} peças).`}).catch(()=>{dirty=true;$('gen-folder-status').textContent='Não foi possível gravar na pasta. As peças continuam salvas neste navegador; use Baixar JSON desta sessão.'});return writing}
 $('gen-download').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([fileText()],{type:'application/json'}));a.href=url;a.download=`${sessionName||'polyiamonds-gerador'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)};
 function showLatest(item){const t=item.row.tiling;try{$('gen-latest').innerHTML=patchSVG(t,{width:150,height:100,unit:3,palette:'terra',gridWidth:.05,outline:.5,title:item.row.pieceId,corners:false}).svg}catch{$('gen-latest').innerHTML=tileSVG(t.prototype)}$('gen-latest-ref').textContent=`${item.row.pieceId.slice(0,25)} · ${+item.row.pieceId.slice(1,4)} △ · ${item.family}`}
 function renderList(){const recent=session.slice(-24).reverse();$('gen-list').replaceChildren(...recent.map(r=>{const a=document.createElement('a');a.className='tile';a.href='?find='+encodeURIComponent(r.pieceId);a.setAttribute('aria-label',`${r.pieceId.slice(0,25)}, ${+r.pieceId.slice(1,4)} triângulos`);a.innerHTML=tileSVG(r.tiling.prototype,{thumb:true})+`<span>${+r.pieceId.slice(1,4)} △</span>`;return a}));$('gen-count').textContent=fmt(session.length)}
 // Grava em lotes no IndexedDB para não travar a página em gerações longas.
 function flush(){if(flushing||!queue.length)return flushing;const batch=queue.splice(0);flushing=insertGenerated(batch.map(x=>x.row)).then(added=>{const ids=new Set(added.map(r=>r.pieceId));for(const x of batch)if(ids.has(x.row.pieceId)){session.push(x.row);pieces.push([x.attempt,x.n,x.check]);dirty=true}if(added.length){renderList();if(Date.now()-latestShown>1500){showLatest(batch.filter(x=>ids.has(x.row.pieceId)).pop());latestShown=Date.now()}}controls();status()}).catch(e=>{stop('error');$('gen-status').textContent=userError(e)}).finally(()=>{flushing=null;if(queue.length)flush()});return flushing}
 function tick(){if(state!=='running')return;const now=performance.now();remaining-=now-lastTick;lastTick=now;showClock();if(queue.length>=25)flush();if(dir&&dirty&&Date.now()-lastWrite>60000)writeFolder();if(remaining<=0)stop('done')}
 async function stop(reason){if(state==='idle')return;clearInterval(timer);timer=null;for(const w of workers)w.terminate();workers=[];state='idle';releaseWake();await flush();await flushing;dirty=true;await writeFolder();remaining=Math.max(0,remaining);controls();$('gen-clock').textContent=clock(remaining);
  if(reason==='done'){$('gen-progress').value=1;$('gen-status').textContent=`Tempo concluído: ${fmt(saved())} peças novas salvas.`}else if(reason==='cancel')$('gen-status').textContent=`Geração cancelada: ${fmt(saved())} peças novas salvas.`;
  if(!dir&&session.length)$('gen-folder-status').textContent='Para incluir estas peças na próxima atualização do site, baixe o JSON desta sessão e salve-o na pasta DiscoveriesInbox.'}
 // Mostra quais simetrias são possíveis nas ordens escolhidas (ex.: 95 triângulos não admite p3/p6).
 function families(){const a=+$('gen-min').value,b=+$('gen-max').value;if(!(a>=22&&b<=200&&a<=b)){$('gen-families').textContent='';return true}const set=new Set();for(let n=a;n<=b&&set.size<6;n++)for(const f of familiesFor(n))set.add(f);const wanted=SYMMETRIES[$('gen-symmetry').value].filter(f=>set.has(f));$('gen-families').textContent=wanted.length?`Simetrias possíveis: ${wanted.join(', ')}`:'Nenhuma simetria desta opção é possível para essas ordens. Escolha Variada ou outra faixa.';return wanted.length>0}
 for(const id of['gen-min','gen-max','gen-symmetry'])$(id).addEventListener('change',families);families();
 $('gen-time').onchange=showClock;
 $('gen-start').onclick=async()=>{const nMin=+$('gen-min').value,nMax=+$('gen-max').value;if(!$('gen-min').checkValidity()||!$('gen-max').checkValidity()||!Number.isInteger(nMin)||!Number.isInteger(nMax)||nMin>nMax){$('gen-status').textContent='Escolha ordens inteiras de 22 a 200, com mínimo menor ou igual ao máximo.';return}if(!families()){$('gen-status').textContent='Nenhuma simetria desta opção é possível para essas ordens. Escolha Variada ou outra faixa.';return}
  if(dir&&!await authorize())$('gen-folder-status').textContent='A pasta não foi autorizada. As peças serão salvas neste navegador; use Baixar JSON desta sessão.';
  state='loading';controls();$('gen-start').hidden=true;$('gen-status').textContent='Carregando as peças já conhecidas…';
  try{known=new Set();for(let n=nMin;n<=nMax;n++){for(const e of await discoveryRows(n))if(e.pieceId.startsWith('L'))known.add(e.pieceId.slice(5,25));for(const x of await recipeItems(n))known.add(x.id.slice(5,25))}for(const x of(await bookCatalogue()).items)if(x.n>=nMin&&x.n<=nMax)known.add((await sha(shapeKey(x.code))).slice(0,20))}catch(e){state='idle';controls();$('gen-status').textContent=userError(e);return}
  const stamp=new Date(),p=n=>String(n).padStart(2,'0');sessionName=`polyiamonds-gerador-${stamp.getFullYear()}-${p(stamp.getMonth()+1)}-${p(stamp.getDate())}-${p(stamp.getHours())}${p(stamp.getMinutes())}${p(stamp.getSeconds())}`;session=[];pieces=[];stats=new Map();renderList();
  recipe={generator:GENERATOR,seed:crypto.getRandomValues(new Uint32Array(1))[0]>>>0,nMin,nMax,style:$('gen-style').value,symmetry:$('gen-symmetry').value,startedAt:stamp.toISOString()};const cores=+$('gen-cores').value,keys=[...known];
  for(let i=0;i<cores;i++){const w=new Worker(new URL('./forge-worker.mjs?v=a24c21ddc48f',import.meta.url),{type:'module'}),id=i;w.onmessage=({data:d})=>{if(d.type==='progress')stats.set(id,d.examined);else if(d.type==='found'){if(known.has(d.check))return;known.add(d.check);for(const o of workers)if(o!==w)o.postMessage({type:'known',keys:[d.check]});queue.push(d)}else if(d.type==='error'){stop('error');$('gen-status').textContent=userError({message:d.message})}};w.onerror=()=>{stop('error');$('gen-status').textContent='O gerador foi interrompido. As peças já salvas continuam no histórico.'};w.postMessage({type:'start',options:{...recipe,start:i,step:cores,pick:+$('gen-pick').value},known:keys});workers.push(w)}
  total=remaining=+$('gen-time').value*1000;lastTick=performance.now();state='running';timer=setInterval(tick,250);keepAwake();controls();showClock();status()};
 $('gen-pause').onclick=()=>{if(state==='running'){tick();state='paused';for(const w of workers)w.postMessage({type:'pause'});releaseWake();flush()}else if(state==='paused'){state='running';lastTick=performance.now();for(const w of workers)w.postMessage({type:'resume'});keepAwake()}controls();status()};
 $('gen-cancel').onclick=()=>stop('cancel');
 setInterval(()=>{if(state==='running')status()},1000);
 showClock();controls()}
