import {colorTiles} from './coloring.mjs?v=a24c21ddc48f';
export const H=Math.sqrt(3)/2;
export const DIR=[[1,-1],[1,0],[0,1],[-1,1],[-1,0],[0,-1]];
export function polygon(code){let a=0,b=0;return [...code].map(c=>{const p=[a,b];a+=DIR[+c-1][0];b+=DIR[+c-1][1];return p})}
export function xy([a,b],unit=1){return [H*a*unit,-(b+a/2)*unit]}
export function path(code,a=0,b=0,unit=1){return polygon(code).map(([x,y],i)=>`${i?'L':'M'}${xy([x+a,y+b],unit).map(f).join(' ')}`).join('')+'Z'}
const f=x=>Number(x.toFixed(5));
export function inside(x,y,p){let c=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const [a,b]=p[i],[u,v]=p[j];if((b>y)!=(v>y)&&x<(u-a)*(y-b)/(v-b)+a)c=!c}return c}
export function cells(code){const p=polygon(code),out=[];for(let a=Math.min(...p.map(p=>p[0]));a<Math.max(...p.map(p=>p[0]));a++)for(let b=Math.min(...p.map(p=>p[1]));b<Math.max(...p.map(p=>p[1]));b++)for(let t=0;t<2;t++)if(inside(a+(1+t)/3,b+(1+t)/3,p))out.push([a,b,t]);return out}
export function bounds(code,unit=1){const p=polygon(code).map(p=>xy(p,unit));return [Math.min(...p.map(p=>p[0])),Math.min(...p.map(p=>p[1])),Math.max(...p.map(p=>p[0])),Math.max(...p.map(p=>p[1]))]}
export function grid(x,y,w,h,unit){let d='';const amin=Math.floor(x/(H*unit))-2,amax=Math.ceil((x+w)/(H*unit))+2;const bmin=Math.floor(-((y+h)/unit)-amax/2)-2,bmax=Math.ceil(-y/unit-amin/2)+2;const edges=new Set();for(let a=amin;a<=amax;a++)for(let b=bmin;b<=bmax;b++)for(const [da,db] of [[1,0],[0,1],[1,-1]]){const p=xy([a,b],unit),q=xy([a+da,b+db],unit);if(Math.max(p[0],q[0])<x||Math.min(p[0],q[0])>x+w||Math.max(p[1],q[1])<y||Math.min(p[1],q[1])>y+h)continue;const k=[a,b,da,db].join(',');if(!edges.has(k)){edges.add(k);d+=`M${p.map(f).join(' ')}L${q.map(f).join(' ')}`}}return d}
function reduce(u,v){let U=[...u],V=[...v];const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+(a[0]*b[1]+a[1]*b[0])/2;for(let k=0;k<100;k++){if(dot(V,V)<dot(U,U))[U,V]=[V,U];const m=Math.round(dot(U,V)/dot(U,U));if(!m)break;V=V.map((x,i)=>x-m*U[i])}return [U,V]}
export function placements(tiling,width,height,unit){if(!tiling)return [];const [U,V]=reduce(tiling.u,tiling.v),[ux,uy]=xy(U,unit),[vx,vy]=xy(V,unit),det=ux*vy-uy*vx,out=[];let attempts=0;for(let m=0;m<tiling.motifs.length;m++){const [code,a,b]=tiling.motifs[m],bb=bounds(code,unit),[ox,oy]=xy([a,b],unit);const corners=[[-bb[2]-ox,-bb[3]-oy],[width-bb[0]-ox,-bb[3]-oy],[-bb[2]-ox,height-bb[1]-oy],[width-bb[0]-ox,height-bb[1]-oy]].map(([x,y])=>[(x*vy-y*vx)/det,(ux*y-uy*x)/det]);const loI=Math.floor(Math.min(...corners.map(c=>c[0]))),hiI=Math.ceil(Math.max(...corners.map(c=>c[0]))),loJ=Math.floor(Math.min(...corners.map(c=>c[1]))),hiJ=Math.ceil(Math.max(...corners.map(c=>c[1])));for(let i=loI;i<=hiI;i++)for(let j=loJ;j<=hiJ;j++){if(++attempts>200000)throw Error('Área muito grande. Aumente o lado do triângulo ou reduza o patch.');const A=a+i*U[0]+j*V[0],B=b+i*U[1]+j*V[1],[x,y]=xy([A,B],unit);if(x+bb[2]<=0||x+bb[0]>=width||y+bb[3]<=0||y+bb[1]>=height)continue;out.push({code,a:A,b:B,m});if(out.length>15000)throw Error('Limite de 15.000 peças por patch. Reduza as dimensões.')}}return out}
export const palettes={azul:['#3b61be','#7c9fe0','#b8ceef','#e6b852','#dfecff','#254483'],terra:['#bc572c','#e3a04b','#f3d398','#71878c','#b2c5c4','#874531'],mono:['#dedfe4','#b5bac7','#8a94a9','#eff0f4','#cdd2df','#a3acc0']};
palettes.bw=Array(100).fill('#ffffff');
export function patchSVG(tiling,{width,height,unit,palette='azul',gridWidth=.18,outline=.45,title='Polyiamond',corners=true}){const tiles=placements(tiling,width,height,unit),colors=Array.isArray(palette)?palette:palettes[palette],coloring=colorTiles(tiles,corners);let fills='',lines='';tiles.forEach((t,i)=>{const d=path(t.code,t.a,t.b,unit);fills+=`<path id="peca-${i+1}" data-motif="${t.m}" data-color="${coloring.colors[i]}" d="${d}" fill="${colors[coloring.colors[i]]||`hsl(${(coloring.colors[i]*137.508)%360} 50% 62%)`}"/>`;lines+=`<path d="${d}"/>`});const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}mm" height="${height}mm" viewBox="0 0 ${width} ${height}"><title>${title}</title><desc>Malha de triângulos equiláteros; lado ${unit} mm. Dimensões ${width} × ${height} mm. Peças cortadas na borda por máscara vetorial. ${tiling?(tiling.source?.file||'Laboratório geométrico'):'Sem tesselação documentada.'}</desc><defs><clipPath id="limite"><rect width="${width}" height="${height}"/></clipPath></defs><g clip-path="url(#limite)"><g id="fundo"><rect width="${width}" height="${height}" fill="#ffffff"/></g><g id="pecas" fill-rule="evenodd">${fills}</g><g id="malha-triangular" fill="none" stroke="#334155" stroke-width="${gridWidth}" stroke-linecap="round"><path d="${grid(0,0,width,height,unit)}"/></g><g id="contornos" fill="none" stroke="#172c50" stroke-width="${outline}" stroke-linejoin="round">${lines}</g></g></svg>`;return {svg,count:tiles.length,colorCount:coloring.count}}
export function tileSVG(code,{thumb=false}={}){const unit=20,[x,y,r,b]=bounds(code,unit),pad=thumb?8:25,w=r-x+2*pad,h=b-y+2*pad;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${x-pad} ${y-pad} ${w} ${h}" role="img" aria-label="Prototile na malha triangular"><path d="${path(code,0,0,unit)}" fill="#a6c1f0" fill-rule="evenodd"/><path d="${grid(x-pad,y-pad,w,h,unit)}" fill="none" stroke="#526784" stroke-width="${thumb?.45:.4}"/><path d="${path(code,0,0,unit)}" fill="none" stroke="#1c3871" stroke-width="${thumb?1.7:1.5}" stroke-linejoin="round"/></svg>`}
