import {translations} from './translations.mjs?v=e12bec2b718e';
const clean=s=>s.replace(/\s+/g,' ').trim(),escape=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const patterns=Object.keys(translations).filter(k=>k.includes('{')).map(k=>({k,re:new RegExp('^'+k.split(/(\{\d+\})/).map(p=>/^\{\d+\}$/.test(p)?'(.+?)':escape(p)).join('')+'$')}));
const originals=new WeakMap(),attrs=new WeakMap();let observed,observer;export const unknown=new Set();
const language=()=>({en:'en',pt:'pt',es:'es',de:'de'}[document.documentElement.lang.split('-')[0]]||'en');
export function translate(text,depth=0){const l=language(),s=clean(text);if(!s||l==='pt')return text;const i={en:0,es:1,de:2}[l];let result=translations[s]?.[i];if(result===undefined)for(const p of patterns){const m=s.match(p.re);if(m){result=translations[p.k][i].replace(/\{(\d+)\}/g,(_,n)=>depth<6?translate(m[+n+1],depth+1):m[+n+1]);break}}
 if(result===undefined&&depth<3){const suffix=s.match(/^(.*?)( \(\d[\d.,]*\))$/);if(suffix){const a=translate(suffix[1],depth+1);result=a+suffix[2]}if(result===undefined&&s.includes(' · ')){const parts=s.split(' · ');const a=parts.map(x=>translate(x,depth+1)).join(' · ');result=a}}
 if(result===undefined&&/^\d{1,3}(?:\.\d{3})+$/.test(s))result=new Intl.NumberFormat(l).format(Number(s.replace(/\./g,'')));if(result===undefined){if(/[À-ÖØ-öø-ÿ]|\b(peça|peças|busca|histórico|padrão|salvo|salvos|triângulos)\b/i.test(s)&&!s.includes('.ps')&&!s.includes('.pdf'))unknown.add(s);return text}return text.replace(text.trim(),result)
}
function paint(root){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(w.nextNode()){const n=w.currentNode;if(n.parentElement?.closest('script,style,code,pre'))continue;const saved=originals.get(n),source=saved&&n.nodeValue===saved.output?saved.source:n.nodeValue,output=translate(source);originals.set(n,{source,output});if(n.nodeValue!==output)n.nodeValue=output}for(const el of root.querySelectorAll('[aria-label],[title],[placeholder]'))for(const a of['aria-label','title','placeholder']){if(!el.hasAttribute(a))continue;const old=attrs.get(el)||{},current=el.getAttribute(a),source=old[a]&&current===old[a].output?old[a].source:current,output=translate(source);old[a]={source,output};attrs.set(el,old);if(current!==output)el.setAttribute(a,output)}}
export function localize(root){if(!root)return;observer?.disconnect();observed=root;paint(root);if(!observer)observer=new MutationObserver(()=>{observer.disconnect();paint(observed);observer.observe(observed,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['aria-label','title','placeholder']})});observer.observe(root,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['aria-label','title','placeholder']})}
export function translateMarkup(markup){const doc=new DOMParser().parseFromString(markup,'image/svg+xml');paint(doc.documentElement);return new XMLSerializer().serializeToString(doc.documentElement)}

export function userError(error){return translations[clean(error?.message||'')]?error.message:'Não foi possível concluir esta operação. Tente novamente.'}
