import {userError} from './i18n.mjs?v=e12bec2b718e';
import {shapeKey,startingCells} from './lab-core.mjs?v=e12bec2b718e';
import {api} from './storage.mjs?v=e12bec2b718e';
import {tileSVG} from './geometry.mjs?v=e12bec2b718e';
const $=id=>document.getElementById(id);let worker=null,running=false,pending=null,saving=false,serial=0,results=[],onSelect=()=>{};
const message=s=>$('lab-status').textContent=s;
function controls(){$('lab-start').disabled=!!worker||saving;$('lab-pause').hidden=!worker;$('lab-pause').disabled=saving||!!pending;$('lab-pause').textContent=running?'Pausar':'Retomar exploração';$('lab-reset').hidden=!worker;$('lab-retry').hidden=!pending||saving;$('lab-n').disabled=saving}
function kill(){worker?.terminate();worker=null;running=false;pending=null;saving=false;serial++;controls()}
function item(e){return{id:e.pieceId,n:+e.pieceId.slice(1,4),code:e.tiling.prototype,categories:['experimental'],sources:[],tilings:[{...e.tiling,fingerprint:e.fingerprint,createdAt:e.createdAt}]}}
function render(){$('lab-results').replaceChildren(...results.map(e=>{const b=document.createElement('button');b.className='tile';b.setAttribute('aria-label',`Explorar peça de ${+e.pieceId.slice(1,4)} triângulos, ${e.fingerprint.slice(0,6)}`);b.innerHTML=tileSVG(e.tiling.prototype,{thumb:true})+`<span>${e.fingerprint.slice(0,6)}</span>`;b.onclick=()=>onSelect(item(e));return b}));$('lab-count').textContent=results.length===1?'1 registro recente':`${results.length} registros recentes`;}
async function load(){const ticket=serial,n=+$('lab-n').value;try{const data=await api(`/api/lab?n=${n}`);if(ticket!==serial)return;results=data.entries;render()}catch{if(ticket===serial)message('Não foi possível carregar o histórico. Tente novamente.')}}
async function save(){if(!pending||saving)return;saving=true;controls();const payload=pending,ticket=serial;try{const data=await api('/api/lab',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(30000)});if(ticket!==serial)return;saving=false;if(data.status===409){pending=null;controls();if(running){message('Forma já conhecida nesta base. Explorando outra…');worker?.postMessage({type:'resume'})}return}if(data.status!==201)throw Error(data.error||'Falha no salvamento.');pending=null;running=false;const e=data.entry;results=[e,...results].slice(0,10000);render();onSelect(item(e));message(`Nova peça de ${payload.n} triângulos salva com tesselação validada. Exploração pausada; use Retomar para procurar outra.`);controls()}catch(e){if(ticket!==serial)return;saving=false;running=false;message('O candidato está na memória, mas o salvamento não foi confirmado. Use Repetir salvamento.');controls()}}
export function setupLab(select){onSelect=select;$('lab-start').onclick=async()=>{if(!$('lab-n').checkValidity()){message('Escolha uma ordem inteira de 22 a 200.');return}kill();const ticketLoad=serial;const n=+$('lab-n').value;let history;try{history=await api(`/api/lab?n=${n}`)}catch(e){message(userError(e));return}if(ticketLoad!==serial)return;results=history.entries;render();worker=new Worker(new URL('./lab-worker.mjs?v=e12bec2b718e',import.meta.url),{type:'module'});running=true;const ticket=serial;worker.onmessage=({data:r})=>{if(ticket!==serial)return;if(r.type==='candidate'){pending={n,code:r.code,tiling:r.tiling,config:{seed, maxTiles:2, checkpoint:r.checkpoint}};message('Peça encontrada. Verificando novidade no histórico…');save()}else if(r.type==='progress'&&running)message(`Computando neste computador · ${r.attempts.toLocaleString('pt-BR')} tentativas · ${r.accepted} mudanças válidas.`);else if(['error','limit'].includes(r.type)){kill();message(userError({message:r.message}))}};worker.onerror=()=>{kill();message('A exploração foi interrompida. As descobertas salvas continuam no histórico.')};const seed=crypto.getRandomValues(new Uint32Array(1))[0]||1;worker.postMessage({type:'start',n,config:{seed,startCells:results.map(e=>startingCells(n,e.tiling)).find(Boolean)},known:results.map(e=>shapeKey(e.tiling.prototype))});message('Explorando peças na memória deste computador…');controls()};$('lab-pause').onclick=()=>{if(!worker)return;running=!running;worker.postMessage({type:running?'resume':'pause'});message(running?'Retomando a exploração…':'Pausada na memória deste computador. Mantenha a aba aberta para retomar.');controls()};$('lab-reset').onclick=()=>{kill();message('Sessão encerrada. As descobertas salvas permanecem no histórico.')};$('lab-n').onchange=()=>{kill();results=[];render();message('Escolha Explorar novas peças para começar.');if($('lab-n').checkValidity())load()};$('lab-retry').onclick=save;load();controls()}
