import {colorTiles} from './coloring.mjs?v=e12bec2b718e';
import {placements,path,grid,xy,palettes} from './geometry.mjs?v=e12bec2b718e';
const encoder=new TextEncoder(),mm=72/25.4;
const number=n=>Number(n.toFixed(4));
// WinAnsi core font text, hex encoded so accents and delimiters are unambiguous.
function hex(text){const special={'–':150,'—':151,'…':133,'’':146};return [...text].map(c=>(special[c]||((c.charCodeAt(0)<256)?c.charCodeAt(0):63)).toString(16).padStart(2,'0')).join('')}
function text(s,x,y,size=2.4){return `BT /F1 ${size} Tf 1 0 0 -1 ${x} ${y} Tm <${hex(s)}> Tj ET\n`}
function vector(d){return [...d.matchAll(/([ML])(-?[\d.]+) (-?[\d.]+)|(Z)/g)].map(m=>m[4]?'h':`${m[2]} ${m[3]} ${m[1]==='M'?'m':'l'}`).join('\n')+'\n'}
function rgb(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(number).join(' ')}
export function pageDrawing(records,{page,total,heading,note,gridWidth=.08,caption,date='',color=false,palette='azul',width=240,height=180,unit=10,corners=false}){let s=`q ${mm} 0 0 ${-mm} 0 ${420*mm} cm\n0 g\n`+text(heading,12,12,4)+text(note,12,17,2.3);records.forEach((r,i)=>{const x=12+(i%4)*69.25,y=23+Math.floor(i/4)*47.25,w=65.25,h=35,scale=Math.min(w/width,h/height),dx=(w-width*scale)/2,dy=(h-height*scale)/2,tiles=placements(r.tiling,width,height,unit),shapes=new Map();for(const t of tiles)if(!shapes.has(t.code))shapes.set(t.code,vector(path(t.code,0,0,unit)));s+=`q ${scale} 0 0 ${scale} ${x+dx} ${y+dy} cm\n0 0 ${width} ${height} re W n\n`;
 const draw=(t,op)=>{const[tx,ty]=xy([t.a,t.b],unit);return `q 1 0 0 1 ${number(tx)} ${number(ty)} cm\n`+shapes.get(t.code)+op+' Q\n'};
 if(color){const colors=Array.isArray(palette)?palette:palettes[palette],c=colorTiles(tiles,corners);tiles.forEach((t,j)=>{const index=c.colors[j],hex=colors[index]||extraColor(index);s+=rgb(hex)+' rg\n'+draw(t,'f*')})}
 s+=`.72 G ${gridWidth/scale} w\n`+vector(grid(0,0,width,height,unit))+'S\n'+`.12 G ${.18/scale} w 1 j\n`;for(const t of tiles)s+=draw(t,'S');s+='Q\n0 g\n'+text(r.piece,x,y+38,2.35)+text(`T-${r.id.slice(0,20)}`,x,y+41,2.35)+text(caption(r),x,y+44,2.15)});s+=text(`Zonneveld Manufactura - Polyiamonds`,12,408,2.5)+text(date,12,412,2.3)+text(`${page} / ${total}`,270,410,2.5)+'Q';return s}
export function extraColor(i){const v=[0,2,4].map(j=>Math.round((Math.sin(i*2.4+j)+1)*85+40));return '#'+v.map(x=>x.toString(16).padStart(2,'0')).join('')}
async function compress(s){const stream=new Blob([s]).stream().pipeThrough(new CompressionStream('deflate'));return new Uint8Array(await new Response(stream).arrayBuffer())}
export async function createPDF(records,options={},progress=()=>{}){if(!records.length)throw Error('Nenhuma tesselação disponível para o PDF.');const total=Math.ceil(records.length/32),objects=[null,encoder.encode('<< /Type /Catalog /Pages 2 0 R >>'),null,encoder.encode('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>')],kids=[];let bytes=0;
 for(let p=0;p<total;p++){const drawing=pageDrawing(records.slice(p*32,p*32+32),{...options,page:p+1,total}),packed=await compress(drawing);bytes+=packed.length;if(bytes>192*1024*1024)throw Error('PDF muito grande. Exporte uma ordem por vez.');const contentId=objects.length;objects.push([encoder.encode(`<< /Length ${packed.length} /Filter /FlateDecode >>\nstream\n`),packed,encoder.encode('\nendstream')]);const id=objects.length;objects.push(encoder.encode(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${297*mm} ${420*mm}] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentId} 0 R >>`));kids.push(`${id} 0 R`);progress(p+1,total)}
 objects[2]=encoder.encode(`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${total} >>`);const chunks=[encoder.encode('%PDF-1.4\n% Vector polyiamonds\n')],offsets=[0];let offset=chunks[0].length;for(let i=1;i<objects.length;i++){offsets.push(offset);const parts=[encoder.encode(`${i} 0 obj\n`),...[objects[i]].flat(),encoder.encode('\nendobj\n')];for(const a of parts){chunks.push(a);offset+=a.length}}
 const xref=offset;chunks.push(encoder.encode(`xref\n0 ${objects.length}\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`));return new Blob(chunks,{type:'application/pdf'})}
