import {userError} from './i18n.mjs?v=e12bec2b718e';
import {api} from './storage.mjs?v=e12bec2b718e';
import{canonical}from'./search-core.mjs?v=e12bec2b718e';
const $=id=>document.getElementById(id);let worker=null,timer=null,item=null,ready=false,pending=null,config=null,serial=0,deadline=0,clockActive=false,found=0,onSaved=()=>{},entries=[],paused=false,remaining=30000;
const message=s=>$('search-status').textContent=s;
function state(busy){$('search-new').disabled=busy||!ready;$('search-stop').hidden=!busy;$('search-pause').hidden=!busy;$('search-pause').textContent=paused?'Retomar':'Pausar';$('search-pause').disabled=!!pending;$('search-size').disabled=busy;$('search-time').disabled=busy;$('search-memory').disabled=busy;$('allow-reflections').disabled=busy}
function suspendClock(){if(clockActive){remaining=Math.max(0,deadline-Date.now());clockActive=false}clearTimeout(timer);timer=null}
function resumeClock(){clearTimeout(timer);deadline=Date.now()+remaining;clockActive=true;if(Number.isFinite(remaining))timer=setTimeout(()=>stop('Tempo ativo esgotado, sem novo padrão salvo. Isso não prova impossibilidade.'),remaining)}
function stop(text){if(worker)worker.terminate();worker=null;paused=false;suspendClock();state(false);if(text)message(text)}
export function setupSearch(callback){onSaved=callback;$('search-new').onclick=start;$('search-stop').onclick=()=>stop('Busca interrompida. Os padrões já salvos permanecem no histórico.');$('retry-save').onclick=()=>savePending();$('search-pause').onclick=()=>{if(!worker||pending)return;paused=!paused;if(paused){suspendClock();worker.postMessage({type:'pause'});message('Busca pausada na memória deste computador. Mantenha esta aba aberta para retomar.')}else{resumeClock();worker.postMessage({type:'resume'});message('Retomando a busca de onde parou…')}state(true)}}
export async function selectSearchItem(x){serial++;stop();item=x;ready=false;pending=null;entries=[],paused=false,remaining=30000;$('retry-save').hidden=true;$('history-list').replaceChildren();$('history-count').textContent='Carregando…';message('Consultando o histórico salvo…');state(false);if(!x){message('Selecione uma peça para buscar.');$('history-count').textContent='Sem peça';return}const ticket=serial;try{const data=await api(`/api/history?piece=${encodeURIComponent(x.id)}`);if(ticket!==serial)return;entries=data.entries;renderHistory(data.total);onSaved(entries,null,x.id);ready=true;state(false);if(x.categories.includes('nontile')||x.categories.includes('holes')){$('search-new').disabled=true;message('Esta peça não tessela o plano segundo a fonte; o prototile continua disponível.')}else{const morphic=x.categories.find(c=>c.endsWith('-morphic'));message(morphic?`O catálogo já contém as ${morphic.split('-')[0]} tesselações desta peça. A busca pode reencontrá-las, mas não as salvará como novas.`:'Pronto para buscar. Só serão salvos arranjos diferentes dos padrões já registrados.')}}catch(e){if(ticket!==serial)return;message(userError(e)+' Selecione a peça novamente para tentar carregar.');$('history-count').textContent='Indisponível';state(false)}}
function renderHistory(total){$('history-count').textContent=`${total} salvo${total===1?'':'s'}`;$('history-total').textContent=`(${total})`;$('history-list').replaceChildren(...entries.map(e=>{const b=document.createElement('button');b.textContent=`${e.fingerprint.slice(0,8)} · ${new Date(e.createdAt).toLocaleString('pt-BR')}`;b.onclick=()=>onSaved(entries,e.fingerprint,item.id);return b}));if(!entries.length)$('history-list').textContent='Ainda não há descobertas salvas para esta peça.';if(total>entries.length){const p=document.createElement('p');p.className='help';p.textContent='Mostrando os 100 mais recentes. Todos os registros continuam protegidos contra duplicação.';$('history-list').append(p)}}
function start(){if(!item||!ready)return;stop();pending=null;$('retry-save').hidden=true;config={maxTiles:+$('search-size').value,reflections:$('allow-reflections').checked,seed:crypto.getRandomValues(new Uint32Array(1))[0]||1,maxNodes:5000000,maxSolutions:10000,memoryMB:+$('search-memory').value};const known=[...item.tilings.filter(t=>t.category!=='generated').map(canonical),...entries.map(e=>e.canonical)];worker=new Worker(new URL('./search-worker.mjs?v=e12bec2b718e',import.meta.url),{type:'module'});const ticket=serial;found=0;state(true);message('Buscando combinações na malha triangular…');remaining=+$('search-time').value?+$('search-time').value*1000:Infinity;resumeClock();worker.onmessage=e=>{if(ticket!==serial||!worker)return;const r=e.data;if(r.type==='paused')return;if(r.type==='candidate'){found++;pending={pieceId:item.id,tiling:r.tiling,config};message('Padrão candidato encontrado. Verificando novidade e salvando no histórico…');savePending()}else if(r.type==='progress'){if(!paused)message(`Buscando: ${r.nodes.toLocaleString('pt-BR')} etapas · ${r.solutions} soluções examinadas · repetição com ${r.cellTiles} peças.`)}else if(r.type==='error')stop(userError({message:r.message}));else stop(r.type==='exhausted'?'Busca concluída dentro do tamanho configurado, sem novo padrão. Tente uma repetição maior.':'Limite de esforço atingido, sem novo padrão salvo. Tente novamente ou aumente o tamanho da repetição.')};worker.onerror=()=>stop('Falha na busca. Tente novamente.');worker.postMessage({type:'start',code:item.code,config,known})}
async function savePending(){if(!pending)return;const payload=pending,ticket=serial;suspendClock();$('retry-save').hidden=true;state(true);try{const data=await api('/api/patterns',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(ticket!==serial||pending!==payload)return;if(data.status===409){pending=null;state(!!worker);if(worker){if(remaining<=0){stop('Limite de tempo atingido. Os candidatos encontrados já estavam na base.');return}if(!paused)resumeClock();message(paused?'Busca pausada na memória deste computador.':'Esse candidato já existe na base. Continuando a busca…');worker.postMessage({type:'continue'})}else{const latest=await api(`/api/history?piece=${encodeURIComponent(item.id)}`);if(ticket!==serial)return;entries=latest.entries;renderHistory(latest.total);onSaved(entries,entries.find(e=>e.canonical===canonical(payload.tiling))?.fingerprint,item.id);state(false);message('Esse padrão já estava salvo. Histórico atualizado; nenhuma duplicata foi criada.')}return}pending=null;stop();entries=[data.entry,...entries.filter(e=>e.fingerprint!==data.entry.fingerprint)];const latest=await api(`/api/history?piece=${encodeURIComponent(item.id)}`);if(ticket!==serial)return;entries=latest.entries;renderHistory(latest.total);onSaved(entries,data.entry.fingerprint,item.id);message(`Novo padrão ${data.entry.fingerprint.slice(0,8)} verificado e salvo no histórico salvo. Você já pode exportá-lo como SVG.`)}catch(e){if(ticket!==serial||pending&&pending!==payload)return;stop('Não foi possível confirmar o salvamento. O candidato foi mantido; use “Repetir salvamento”.');pending=payload;$('retry-save').hidden=false}}
