import {cells,polygon,DIR} from './geometry.mjs?v=a24c21ddc48f';
const mod=(x,n)=>((x%n)+n)%n;
const cmp=(a,b)=>a[0]-b[0]||a[1]-b[1];
const gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a);
const det=(u,v)=>u[0]*v[1]-u[1]*v[0];
function egcd(a,b){if(!b)return [Math.abs(a),Math.sign(a),0];const [g,x,y]=egcd(b,a%b);return[g,y,x-Math.trunc(a/b)*y]}
export function lattice(vectors){let D=0;for(let i=0;i<vectors.length;i++)for(let j=0;j<i;j++)D=gcd(D,det(vectors[i],vectors[j]));if(!D)throw Error('Períodos colineares.');let y=0,x=0;for(const [a,b]of vectors){const [g,s,t]=egcd(y,b);x=s*x+t*a;y=g}const a=D/y;return[a,mod(x,a),y]}
export function reducePoint(x,y,[a,b,c]){const j=Math.floor(y/c);return[mod(x-j*b,a),mod(y,c)]}
export function transform([a,b],k=0,mirror=false){if(mirror)[a,b]=[b,a];for(let i=0;i<k;i++)[a,b]=[-b,a+b];return[a,b]}
function tileNorm(points){const sorted=points.slice().sort(cmp);const a=Math.floor(sorted[0][0]/3),b=Math.floor(sorted[0][1]/3);const pts=sorted.map(([x,y])=>[x-3*a,y-3*b]);return{shape:JSON.stringify(pts),points:pts,a,b}}
function arrangement(tiles,L){const map=new Map();for(const t of tiles){const [a,b]=reducePoint(t.a,t.b,L);map.set(`${t.shape}@${a},${b}`,{...t,a,b})}return [...map.values()]}
function minimal(tiles,L){tiles=arrangement(tiles,L);const root=tiles[0];const original=new Set(tiles.map(t=>`${t.shape}@${t.a},${t.b}`));const vecs=[[L[0],0],[L[1],L[2]]];for(const t of tiles){if(t.shape!==root.shape)continue;const dx=t.a-root.a,dy=t.b-root.b;if(!dx&&!dy)continue;if(tiles.every(z=>{const [a,b]=reducePoint(z.a+dx,z.b+dy,L);return original.has(`${z.shape}@${a},${b}`)}))vecs.push([dx,dy])}const small=lattice(vecs);return[small,arrangement(tiles,small)]}
export function canonical(tiling){let L=lattice([tiling.u,tiling.v]);let tiles=tiling.motifs.map(([s,a,b])=>tileNorm(cells(s).map(([x,y,t])=>[3*(x+a)+1+t,3*(y+b)+1+t])));[L,tiles]=minimal(tiles,L);let best=null;for(const mirror of[false,true])for(let k=0;k<6;k++){const R=lattice([transform([L[0],0],k,mirror),transform([L[1],L[2]],k,mirror)]);const ts=arrangement(tiles.map(t=>tileNorm(t.points.map(([x,y])=>transform([x+3*t.a,y+3*t.b],k,mirror)))),R);const minShape=ts.map(t=>t.shape).sort()[0];for(const root of ts){if(root.shape!==minShape)continue;const repr=ts.map(t=>{const [a,b]=reducePoint(t.a-root.a,t.b-root.b,R);return`${t.shape}@${a},${b}`}).sort();const sig=JSON.stringify([1,R,repr]);if(best===null||sig<best)best=sig}}return best}
export function codeAspects(code,reflections=true){const out=new Map();for(const mirror of(reflections?[false,true]:[false]))for(let k=0;k<6;k++){let dirs=[...code].map(c=>transform(DIR[+c-1],k,mirror));let s=dirs.map(v=>String(DIR.findIndex(d=>d[0]===v[0]&&d[1]===v[1])+1)).join('');const cc=cells(s);const a=Math.min(...cc.map(c=>c[0])),b=Math.min(...cc.map(c=>c[1]));const norm=cc.map(([x,y,t])=>[x-a,y-b,t]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]||a[2]-b[2]);const key=JSON.stringify(norm);if(!out.has(key))out.set(key,{code:s,cells:cc,key})}return [...out.values()]}
export function validateTiling(code,tiling,{maxMotifs=512,maxDet=100000}={}){if(!tiling||!Array.isArray(tiling.motifs)||!tiling.motifs.length||tiling.motifs.length>maxMotifs)throw Error('Quantidade de peças inválida.');for(const v of[tiling.u,tiling.v])if(!Array.isArray(v)||v.length!==2||v.some(x=>!Number.isInteger(x)||Math.abs(x)>10000))throw Error('Períodos inválidos.');const L=lattice([tiling.u,tiling.v]),n=cells(code).length;if(L[0]*L[2]>maxDet||tiling.motifs.length*n!==2*L[0]*L[2])throw Error('Área da célula de repetição incorreta.');const aspects=new Set(codeAspects(code).map(t=>t.key));const seen=new Set();for(const m of tiling.motifs){if(!Array.isArray(m)||m.length!==3)throw Error('Motivo inválido.');const[s,a,b]=m;if(typeof s!=='string'||!/^[1-6]{3,402}$/.test(s)||![a,b].every(x=>Number.isInteger(x)&&Math.abs(x)<10000))throw Error('Coordenadas inválidas.');let end=[0,0];for(const c of s){end[0]+=DIR[+c-1][0];end[1]+=DIR[+c-1][1]}if(end[0]||end[1])throw Error('Contorno aberto.');const cc=cells(s),x0=Math.min(...cc.map(c=>c[0])),y0=Math.min(...cc.map(c=>c[1]));const key=JSON.stringify(cc.map(([x,y,t])=>[x-x0,y-y0,t]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]||a[2]-b[2]));if(!aspects.has(key))throw Error('Uma peça não corresponde ao prototile.');for(const [x,y,t]of cc){const [u,v]=reducePoint(a+x,b+y,L);const id=`${u},${v},${t}`;if(seen.has(id))throw Error('Há sobreposição de triângulos.');seen.add(id)}}if(seen.size!==2*L[0]*L[2])throw Error('Há lacunas.');return true}
// Exact cover on a triangular torus. Every accepted solution extends periodically.
// The finite search bound is explicit; exhausting it is not a classification proof.
export function* searchTilings(code,{maxTiles=12,reflections=true,seed=1,maxNodes=500000,maxSolutions=1000,memoryMB=128}={}){const aspects=codeAspects(code,reflections),n=cells(code).length;let nodes=0,solutions=0,memorySkipped=false,buildSteps=0;const rnd=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296};const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
 for(let count=1;count<=maxTiles;count++){if(count*n%2)continue;const area=count*n/2,lattices=[];for(let c=1;c<=area;c++)if(area%c===0){const a=area/c;for(let b=0;b<a;b++)lattices.push([a,b,c])}shuffle(lattices);for(const L of lattices){const [A,B,C]=L,N=2*A*C;const estimated=N/2*aspects.length*(n*24+240);if(estimated>memoryMB*1024*1024){memorySkipped=true;yield{type:'memory',nodes,solutions,cellTiles:count,memoryMB};continue}const rows=[],byCell=Array.from({length:N},()=>[]),seenRows=new Set();for(const asp of aspects)for(let a=0;a<A;a++)for(let b=0;b<C;b++){if(++buildSteps%128===0)yield{type:'tick',nodes,solutions,cellTiles:count};const ids=asp.cells.map(([x,y,t])=>{const[u,v]=reducePoint(x+a,y+b,L);return 2*(u*C+v)+t});if(new Set(ids).size!==n)continue;ids.sort((a,b)=>a-b);const id=rows.length;rows.push({ids,motif:[asp.code,a,b]});for(const c of ids)byCell[c].push(id);if(rows.length%128===0)yield{type:'tick',nodes,solutions,cellTiles:count}}for(const list of byCell)shuffle(list);const used=new Uint8Array(N),chosen=[];
 function* visit(){if(++nodes>maxNodes)return;if(nodes%64===0)yield{type:'tick',nodes,solutions,cellTiles:count};let options=null;for(let c=0;c<N;c++){if(c%64===0)yield{type:'tick',nodes,solutions,cellTiles:count};if(used[c])continue;const opts=byCell[c].filter(i=>rows[i].ids.every(j=>!used[j]));if(!opts.length)return;if(options===null||opts.length<options.length)options=opts;if(options.length===1)break}if(options===null){solutions++;yield{type:'candidate',tiling:{u:[A,0],v:[B,C],motifs:chosen.map(i=>rows[i].motif)},nodes,solutions,cellTiles:count};return}for(const i of options){chosen.push(i);for(const j of rows[i].ids)used[j]=1;yield* visit();for(const j of rows[i].ids)used[j]=0;chosen.pop();if(nodes>maxNodes||solutions>=maxSolutions)return}}
 yield*visit();yield{type:'progress',nodes,solutions,cellTiles:count};if(nodes>maxNodes||solutions>=maxSolutions){yield{type:'limit',nodes,solutions,cellTiles:count};return}}}yield{type:memorySkipped?'limit':'exhausted',nodes,solutions,maxTiles,memorySkipped}}
