import{loadCatalogueOrder,bookCatalogue}from'./collection.mjs?v=e12bec2b718e';
import{canonical,validateTiling}from'./search-core.mjs?v=e12bec2b718e';
import{shapeKey,boundary}from'./lab-core.mjs?v=e12bec2b718e';
import{cells}from'./geometry.mjs?v=e12bec2b718e';
export const localMode=()=>globalThis.POLYIAMONDS_MODE==='local';
let database;
const sha=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
const pad=(n,w)=>String(n).padStart(w,'0');
export const orderOf=id=>+(id.startsWith('P')?id.slice(1,3):id.slice(1,4));
function db(){if(!database)database=new Promise((resolve,reject)=>{const q=indexedDB.open('zonneveld-polyiamonds',1);q.onupgradeneeded=()=>{const s=q.result.createObjectStore('patterns',{keyPath:'fingerprint'});s.createIndex('pieceId','pieceId')};q.onsuccess=()=>{q.result.onversionchange=()=>q.result.close();resolve(q.result)};q.onerror=()=>reject(Error('Não foi possível abrir o histórico deste navegador.'))});return database}
const request=q=>new Promise((resolve,reject)=>{q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});
// Registros deste navegador. Com n, consulta só os prefixos daquela ordem (L/R e, até 99, P).
async function localRows(n){const d=await db(),store=d.transaction('patterns').objectStore('patterns');if(n===undefined)return request(store.getAll());const index=store.index('pieceId'),out=[];for(const p of[`L${pad(n,3)}-`,`R${pad(n,3)}-`,...(n<100?[`P${pad(n,2)}-`]:[])])out.push(...await request(index.getAll(IDBKeyRange.bound(p,p+'￿'))));return out}
async function localOrders(){const d=await db();return new Promise((resolve,reject)=>{const out=[],q=d.transaction('patterns').objectStore('patterns').index('pieceId').openKeyCursor(IDBKeyRange.bound('L','L￿'));q.onsuccess=()=>{const c=q.result;if(!c)return resolve(out);const n=+c.key.slice(1,4);out.push(n);c.continue(`L${pad(n+1,3)}-`)};q.onerror=()=>reject(q.error)})}
// Base publicada: índice discoveries.json (v2) com um arquivo por ordem para as peças novas.
let indexPromise;const shardCache=new Map();
function publishedIndex(){if(!indexPromise)indexPromise=fetch(new URL('./data/discoveries.json?v=e12bec2b718e',import.meta.url)).then(r=>{if(!r.ok)throw Error('Não foi possível carregar os dados. Recarregue a página.');return r.json()}).then(d=>d.version===2?d:{version:1,updated:null,shards:{},entries:d.entries||[]}).catch(e=>{indexPromise=null;throw e});return indexPromise}
const publishedRow=e=>({...e,published:true,tiling:{...e.tiling,category:'generated',source:e.tiling.source||{file:'Busca geométrica',page:0,figure:0}}});
// Cada ordem pode ter várias partes (até 20.000 peças cada): L095.json, L095-2.json…
function part(n,p){const suffix=p>1?'-'+p:'';return fetch(new URL(`./data/discoveries/L${pad(n,3)}${suffix}.json?v=e12bec2b718e`,import.meta.url)).then(r=>{if(!r.ok)throw Error('Não foi possível carregar os dados. Recarregue a página.');return r.json()})}
async function shard(n){const index=await publishedIndex(),info=index.shards?.[n];if(!info)return[];if(!shardCache.has(n))shardCache.set(n,Promise.all(Array.from({length:info.parts||1},(_,i)=>part(n,i+1))).then(list=>list.flatMap(d=>d.entries.map(publishedRow))).catch(e=>{shardCache.delete(n);throw e}));return shardCache.get(n)}
export async function publishedRows(n){const index=await publishedIndex(),base=index.entries.filter(e=>n===undefined||orderOf(e.pieceId)===n).map(publishedRow);if(n!==undefined)return[...base,...await shard(n)];for(const k of Object.keys(index.shards||{}))base.push(...await shard(+k));return base}
export async function catalogueUpdated(){return(await publishedIndex()).updated||null}
export async function discoveryOrders(){const index=await publishedIndex(),set=new Set([...Object.keys(index.shards||{}).map(Number),...index.entries.filter(e=>e.pieceId.startsWith('L')).map(e=>orderOf(e.pieceId))]);if(localMode())for(const n of await localOrders())set.add(n);return[...set].sort((a,b)=>a-b)}
export async function discoveryRows(n){const published=await publishedRows(n),local=localMode()?await localRows(n):[];return [...new Map([...local,...published].map(e=>[e.fingerprint,e])).values()]}
function changed(){globalThis.dispatchEvent?.(new Event('polyiamonds-history'))}
async function insert(row,shapeOnly){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('patterns','readwrite'),s=tx.objectStore('patterns');let added=false;const q=shapeOnly?s.index('pieceId').get(row.pieceId):s.get(row.fingerprint);q.onsuccess=()=>{if(!q.result){const add=s.add(row);add.onsuccess=()=>added=true;add.onerror=e=>{if(add.error.name==='ConstraintError'){e.preventDefault();e.stopPropagation()}}}};tx.oncomplete=()=>resolve(added);tx.onerror=()=>reject(Error('Não foi possível salvar no navegador. Exporte um backup e verifique o espaço disponível.'));tx.onabort=tx.onerror})}
// Gravação em lote do gerador: uma transação, no máximo um registro por forma.
export async function insertGenerated(rows){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('patterns','readwrite'),s=tx.objectStore('patterns'),index=s.index('pieceId'),added=[];for(const row of rows){const q=index.count(row.pieceId);q.onsuccess=()=>{if(q.result)return;const add=s.add(row);add.onsuccess=()=>added.push(row);add.onerror=e=>{if(add.error.name==='ConstraintError'){e.preventDefault();e.stopPropagation()}}}}tx.oncomplete=()=>resolve(added);tx.onerror=()=>reject(Error('Não foi possível salvar no navegador. Exporte um backup e verifique o espaço disponível.'));tx.onabort=tx.onerror})}
async function piece(id){if(/^R\d{3}-[a-f0-9]{20}$/.test(id)){const x=(await bookCatalogue()).items.find(x=>x.id===id);if(x)return x}if(/^P\d{2}-\d{5}$/.test(id)){const item=(await loadCatalogueOrder(+id.slice(1,3))).find(x=>x.id===id);if(item)return item}else if(/^L\d{3}-[a-f0-9]{64}$/.test(id)){const row=(await discoveryRows(orderOf(id))).find(x=>x.pieceId===id);if(row)return{id,n:+id.slice(1,4),code:row.tiling.prototype,categories:[],tilings:[]}}throw Error('Peça não encontrada.')}
async function makeRow(body,lab){let item;if(lab){if(!Number.isInteger(body.n)||body.n<22||body.n>200||typeof body.code!=='string'||!/^[1-6]{3,202}$/.test(body.code))throw Error('Ordem ou contorno inválido.');const cc=cells(body.code);if(cc.length!==body.n||!boundary(cc))throw Error('A peça deve ser conexa e sem furos.');item={id:`L${pad(body.n,3)}-${await sha(shapeKey(body.code))}`,n:body.n,code:body.code,categories:[],tilings:[]}}else item=await piece(body.pieceId);
 validateTiling(item.code,body.tiling,{maxMotifs:64,maxDet:2400});const key=canonical(body.tiling);if(item.tilings.some(t=>canonical(t)===key))return null;
 return{fingerprint:await sha(key),pieceId:item.id,canonical:key,createdAt:new Date().toISOString(),config:{...body.config,storage:'browser'},tiling:{u:body.tiling.u,v:body.tiling.v,motifs:body.tiling.motifs,category:'generated',source:{file:'Busca geométrica',page:0,figure:0},...(item.id.startsWith('L')?{prototype:item.code}:{})}}}
export async function api(path,opts){if(!localMode()){const r=await fetch(path,{...opts,signal:AbortSignal.timeout(20000)}),data=await r.json();if(!r.ok&&r.status!==409)throw Error(data.error||'O histórico está indisponível.');return{...data,status:r.status}}
 const url=new URL(path,'https://local.invalid');if(!opts?.method||opts.method==='GET'){if(url.pathname==='/api/lab'){const n=+url.searchParams.get('n');const rows=(await discoveryRows(n)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return{status:200,entries:rows.filter(x=>x.pieceId.startsWith('L'+pad(n,3)+'-'))}}const selected=await piece(url.searchParams.get('piece')),rows=(await discoveryRows(selected.n)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),entries=rows.filter(x=>x.pieceId===selected.id);return{status:200,entries,total:entries.length,catalogCount:selected.tilings.length}}
 const lab=url.pathname==='/api/lab',body=JSON.parse(opts.body),row=await makeRow(body,lab);if(!row)return{status:409,duplicate:true,reason:'catalog'};if((await discoveryRows(orderOf(row.pieceId))).some(e=>e.fingerprint===row.fingerprint||(lab&&e.pieceId===row.pieceId)))return{status:409,duplicate:true,reason:'history'};if(await insert(row,lab)){changed();return{status:201,entry:row}}return{status:409,duplicate:true,reason:'history'}
}
// O backup contém o histórico deste navegador; a base publicada já está no site.
export async function exportHistory(){return JSON.stringify({format:'zonneveld-polyiamonds',version:1,entries:await localRows()},null,1)}
export async function importHistory(text){if(text.length>64000000)throw Error('Backup muito grande. Limite de 64 MB.');const data=JSON.parse(text);if(data.format!=='zonneveld-polyiamonds'||data.version!==1||!Array.isArray(data.entries)||data.entries.length>50000)throw Error('Backup inválido. Limite de 50.000 registros.');
 const existing=new Set(),validated=[];for(const n of new Set(data.entries.map(x=>typeof x?.pieceId==='string'?orderOf(x.pieceId):NaN).filter(Number.isFinite)))for(const e of await discoveryRows(n))existing.add(e.fingerprint);
 for(const x of data.entries){if(!x||typeof x.pieceId!=='string')throw Error('Backup inválido.');if(existing.has(x.fingerprint))continue;const lab=x.pieceId.startsWith('L');const row=await makeRow(lab?{n:+x.pieceId.slice(1,4),code:x.tiling?.prototype,tiling:x.tiling,config:x.config}:{pieceId:x.pieceId,tiling:x.tiling},lab);if(row){if(row.pieceId!==x.pieceId||row.fingerprint!==x.fingerprint)throw Error('Backup inválido.');if(typeof x.createdAt==='string'&&Number.isFinite(Date.parse(x.createdAt)))row.createdAt=new Date(x.createdAt).toISOString();if(x.tiling?.source?.file&&/^Gerador · [a-z0-9]+$/.test(x.tiling.source.file))row.tiling.source={file:x.tiling.source.file,page:0,figure:0};validated.push(row);existing.add(row.fingerprint)}}
 const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('patterns','readwrite'),s=tx.objectStore('patterns');let added=0;for(const row of validated){const q=s.add(row);q.onsuccess=()=>added++;q.onerror=e=>{if(q.error.name==='ConstraintError'){e.preventDefault();e.stopPropagation()}}}tx.oncomplete=()=>{if(added)changed();resolve(added)};tx.onerror=()=>reject(Error('Não foi possível importar o backup.'));tx.onabort=tx.onerror})}
