import{loadCatalogueOrder,bookCatalogue}from'./collection.mjs?v=20f182d25fc2';
import{canonical,validateTiling}from'./search-core.mjs?v=20f182d25fc2';
import{shapeKey,boundary}from'./lab-core.mjs?v=20f182d25fc2';
import{cells}from'./geometry.mjs?v=20f182d25fc2';
export const localMode=()=>globalThis.POLYIAMONDS_MODE==='local';
let database;
const sha=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
function db(){if(!database)database=new Promise((resolve,reject)=>{const q=indexedDB.open('zonneveld-polyiamonds',1);q.onupgradeneeded=()=>{const s=q.result.createObjectStore('patterns',{keyPath:'fingerprint'});s.createIndex('pieceId','pieceId')};q.onsuccess=()=>{q.result.onversionchange=()=>q.result.close();resolve(q.result)};q.onerror=()=>reject(Error('Não foi possível abrir o histórico deste navegador.'))});return database}
async function localRows(){const d=await db();return new Promise((resolve,reject)=>{const q=d.transaction('patterns').objectStore('patterns').getAll();q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
let publishedPromise;
export async function publishedRows(){if(!publishedPromise)publishedPromise=fetch(new URL('./data/discoveries.json?v=20f182d25fc2',import.meta.url)).then(r=>{if(!r.ok)throw Error('Não foi possível carregar os dados. Recarregue a página.');return r.json()}).then(d=>d.entries.map(e=>({...e,published:true}))).catch(e=>{publishedPromise=null;throw e});return publishedPromise}
export async function discoveryRows(){const published=await publishedRows(),local=localMode()?await localRows():[];return [...new Map([...local,...published].map(e=>[e.fingerprint,e])).values()]}
const all=discoveryRows;
function changed(){globalThis.dispatchEvent?.(new Event('polyiamonds-history'))}
async function insert(row,shapeOnly){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('patterns','readwrite'),s=tx.objectStore('patterns');let added=false;const q=shapeOnly?s.index('pieceId').get(row.pieceId):s.get(row.fingerprint);q.onsuccess=()=>{if(!q.result){const add=s.add(row);add.onsuccess=()=>added=true;add.onerror=e=>{if(add.error.name==='ConstraintError'){e.preventDefault();e.stopPropagation()}}}};tx.oncomplete=()=>resolve(added);tx.onerror=()=>reject(Error('Não foi possível salvar no navegador. Exporte um backup e verifique o espaço disponível.'));tx.onabort=tx.onerror})}
const catalogue=loadCatalogueOrder;
async function piece(id){if(/^R\d{3}-[a-f0-9]{20}$/.test(id)){const x=(await bookCatalogue()).items.find(x=>x.id===id);if(x)return x}if(/^P\d{2}-\d{5}$/.test(id)){const item=(await catalogue(+id.slice(1,3))).find(x=>x.id===id);if(item)return item}else if(/^L\d{3}-[a-f0-9]{64}$/.test(id)){const row=(await all()).find(x=>x.pieceId===id);if(row)return{id,n:+id.slice(1,4),code:row.tiling.prototype,categories:[],tilings:[]}}throw Error('Peça não encontrada.')}
async function makeRow(body,lab){let item;if(lab){if(!Number.isInteger(body.n)||body.n<22||body.n>200||typeof body.code!=='string'||!/^[1-6]{3,202}$/.test(body.code))throw Error('Ordem ou contorno inválido.');const cc=cells(body.code);if(cc.length!==body.n||!boundary(cc))throw Error('A peça deve ser conexa e sem furos.');item={id:`L${String(body.n).padStart(3,'0')}-${await sha(shapeKey(body.code))}`,n:body.n,code:body.code,categories:[],tilings:[]}}else item=await piece(body.pieceId);
 validateTiling(item.code,body.tiling,{maxMotifs:64,maxDet:2400});const key=canonical(body.tiling);if(item.tilings.some(t=>canonical(t)===key))return null;
 return{fingerprint:await sha(key),pieceId:item.id,canonical:key,createdAt:new Date().toISOString(),config:{...body.config,storage:'browser'},tiling:{u:body.tiling.u,v:body.tiling.v,motifs:body.tiling.motifs,category:'generated',source:{file:'Busca geométrica',page:0,figure:0},...(item.id.startsWith('L')?{prototype:item.code}:{})}}}
export async function api(path,opts){if(!localMode()){const r=await fetch(path,{...opts,signal:AbortSignal.timeout(20000)}),data=await r.json();if(!r.ok&&r.status!==409)throw Error(data.error||'O histórico está indisponível.');return{...data,status:r.status}}
 const url=new URL(path,'https://local.invalid');if(!opts?.method||opts.method==='GET'){const rows=(await all()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));if(url.pathname==='/api/lab')return{status:200,entries:rows.filter(x=>x.pieceId.startsWith('L'+url.searchParams.get('n').padStart(3,'0')+'-'))};const selected=await piece(url.searchParams.get('piece')),entries=rows.filter(x=>x.pieceId===selected.id);return{status:200,entries:entries,total:entries.length,catalogCount:selected.tilings.length}}
 const lab=url.pathname==='/api/lab',row=await makeRow(JSON.parse(opts.body),lab);if(!row)return{status:409,duplicate:true,reason:'catalog'};if((await all()).some(e=>e.fingerprint===row.fingerprint||(lab&&e.pieceId===row.pieceId)))return{status:409,duplicate:true,reason:'history'};if(await insert(row,lab)){changed();return{status:201,entry:row}}return{status:409,duplicate:true,reason:'history'}
}
export async function exportHistory(){return JSON.stringify({format:'zonneveld-polyiamonds',version:1,entries:await all()},null,2)}
export async function importHistory(text){if(text.length>64000000)throw Error('Backup muito grande. Limite de 64 MB.');const data=JSON.parse(text);if(data.format!=='zonneveld-polyiamonds'||data.version!==1||!Array.isArray(data.entries)||data.entries.length>50000)throw Error('Backup inválido. Limite de 50.000 registros.');const existing=new Set((await all()).map(e=>e.fingerprint)),validated=[];for(const x of data.entries){if(!x||typeof x.pieceId!=='string')throw Error('Backup inválido.');const lab=x.pieceId.startsWith('L');const row=await makeRow(lab?{n:+x.pieceId.slice(1,4),code:x.tiling?.prototype,tiling:x.tiling,config:x.config}:{pieceId:x.pieceId,tiling:x.tiling},lab);if(row){if(row.pieceId!==x.pieceId||row.fingerprint!==x.fingerprint)throw Error('Backup inválido.');if(typeof x.createdAt==='string'&&Number.isFinite(Date.parse(x.createdAt)))row.createdAt=new Date(x.createdAt).toISOString();if(!existing.has(row.fingerprint))validated.push(row)}}const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('patterns','readwrite'),s=tx.objectStore('patterns');let added=0;for(const row of validated){const q=s.add(row);q.onsuccess=()=>added++;q.onerror=e=>{if(q.error.name==='ConstraintError'){e.preventDefault();e.stopPropagation()}}}tx.oncomplete=()=>{if(added)changed();resolve(added)};tx.onerror=()=>reject(Error('Não foi possível importar o backup.'));tx.onabort=tx.onerror})}
